twitch4j/twitch4j

src/main/java/me/philippheuer/twitch4j/TwitchClient.java
src/main/java/me/philippheuer/twitch4j/chat/IrcClient.java
src/main/java/me/philippheuer/twitch4j/endpoints/TMIEndpoint.java
src/main/java/me/philippheuer/twitch4j/pubsub/TwitchPubSub.java

* Added mod bucket (where limits for moderating chat is 100 per 30 seconds)
* TMIEndpoint#isUserModerator() - returned value is slimmed
* added disconnect() and reconnect() methods, and makes them to public. (Easiest way controlling connection to the Twitch chat for safe disconnect and reconnect.)
Test units are incomplete. So I test it on Raw project, and looks very well.

Mod message bucket, connection management and isUserModerator() slimmed

---

README.md
src/integration/java/me/philippheuer/twitch4j/test/TwitchClientIntegrationTest.java
src/main/java/me/philippheuer/twitch4j/TwitchClientBuilder.java

- setters with prefix `with`
- removing getters (when field is private `@Getter` is not needed here)
- Asserting credentials when you are using `connect()` method
- adding method `addListener()` to adding listeners into dispatcher.
Setters now have prefix `with`. It will be looks like example under:
```java
clientBulder.withClientId("<clientId>")
.withSecret("<clientSecret>")
.withCredentials("<ircCredentials>")
.build() // or .connect()
```

Builder changes

---

src/main/java/me/philippheuer/twitch4j/enums/TwitchScopes.java

I fixed a bug with authorization. It was an issue with one extra "+" char at the end of the "scope" line. 
For example `https://localhost:7090/...&scope=chat_login+"`
After my change it will be: `https://localhost:7090/...&scope=chat_login"`
...

Fixed problem with authorization

---

docs/content/rest-kraken/_index.md
docs/content/rest-kraken/user-get.md
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUserList.java
rest-kraken/src/test/java/kraken/endpoints/UsersServiceTest.java

Added "getUsersByLogin" to TwitchKraken, since the the Helix Users endpoint does not support retrieving the "createdAt" property of a user yet.
...
* [Issue #66 ]
...
* Added getUsersByLogin method to TwitchKraken. This method retrieves User-objects through the Kraken endpoint. This is in order to support retrieving the CreatedAt property of a user, which is not supported by Helix yet. This property is useful for keeping an eye on potential spam accounts.
* Added UserServiceTest integration-test for the above method.
* Added KrakenUserList object, for encapsulating the resulting list from the endpoint.
...

Add feature from issue #66 - Add users endpoint to TwitchKraken

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RaidEvent.java

* Implement a `RaidEvent` for incoming raids that includes the numbers of viewers joining from the raid.
This implementation parses the [IRC raid USERNOTICE as documented here](https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags). Tested in my chat when receiving a raid and event was properly fired with the accurate raid-viewer count.

Implement raid events

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java

* [Issue #77 ]
Tested in a 71k viewer chat by printing `SubscriberEvent`'s fields to console (notably `getMonths()`) and comparing to the notification in chat.
I was unable to test if the current behavior for cumulative months of giftsubs is accurate, but since this PR only changes the code specifically in the `if` conditional for regular (non-gifted) subs, it does not introduce any bugs with giftsubs.

Number of months for resub events is inaccurate #77

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java

* Add method to query consecutive months subscribed.
The Twitch documentation is ambiguous about what value is given for 1st sub in a streak: ["[`msg-param-streak-months`] is 0 if `msg-param-should-share-streak` is 0."](https://dev.twitch.tv/docs/irc/tags/#usernotice-twitch-tags). Since only streaks >= 2 get the option in Twitch chat to "share their streak", the `USERNOTICE` should give 0 for 1st-in-streak subs. This makes sense inside the Twitch API but may confuse some users who would expect a value of 1 in this case. This PR passes the value of `msg-param-streak-months` unchanged to the `SubscriptionEvent`.

Implement sub streaks

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java

* [Issue #82]
* Check for null value before querying instance method.
The bug is very weird. When I do the same thing with `curl`, I get a response body. Also a lot of helix methods are not affected by this. It seems to affect methods that require `user:edit:broadcast` scope, as I discovered it implementing Create Stream Marker and tested that it also occurs with Replace Stream Tags. It's possible the library (maybe Feign?) gets a 401 and stops parsing the body, but with other methods incorrect authentication returned a 401 and the body was parsed correctly. No idea really.

Fix NullPointerException caused by some HTTP 401 responses

---

common/src/main/java/com/github/twitch4j/common/builder/TwitchAPIBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

Not sure about the code style of the project, it works and looks similar, never did any thing builder-related. Not sure if this is the best way to let t4j know about Hystrix config that we want to use.
* Allow users to queue requests instead of throwing exception.
Currently you are able to run 10 requests at the same time; trying to run more throws exception. This is default config of Hystrix. With the changes you are able to queue requests and execute them as soon as the threadpool is freed. You are still limited to 10 requests at the same time.
Example of usage:
`TwitchClientBuilder.builder().withEnableHelix(true).withClientId(SettingsUtil.clientID).withClientSecret(SettingsUtil.clientSecret).withMaxQueueSize(Integer.MAX_VALUE).build();`
```
myList = Collections.synchronizedList(new …
```

Allow queueing synchronous work - queue .execute() instead of exceptions

---

common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Issue #97
* Add a `ChannelPermission` for [Founders](https://help.twitch.tv/s/article/founders-badge)
* Give Founders `ChannelPermission.FOUNDER` and `ChannelPermission.SUBSCRIBER`.
*Founders* is a new chatter type in Twitch chat. Founders are the first 10 subscribers to an affiliate or the first 25 subscribers to a partner. They receive a special badge in chat that replaces their subscriber badge.
If a Founder unsubscribes, they will no longer have the badge on their messages when their subscription expires; however, if they resubscribe, they will regain the badge. Therefore, the presence of the badge on their messages *always* indicates that they are also a subscriber. This implementation assigns messages marked with a Founders badge as having both `ChannelPermission.FOUNDER` and …

Implement support for Twitch Founders badge

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenTeam.java
rest-kraken/src/test/java/kraken/endpoints/TeamServiceTest.java

This caused the displayName, createdAt, and updatedAt properties to not be set from the incoming JSON.
Modified the TeamServiceTest to assert that these properties are being set.
This worked locally, but kept the test with @Disabled annotation.
* Added `@JsonProperty` annotations to `displayName`, `createdAt`, and `updatedAt` to match the snake case of the incoming JSON properties.

Fix for KrakenTeam not having JSON property annotations.

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/AnaylticsDateRange.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BitsLeaderboardEntry.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Extension.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionAnalytics.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Follow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Game.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/GameAnalytics.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/HearthstoneMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Moderator.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/OverwatchMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamMarkers.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamTag.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Subscription.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/User.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/VideoMarker.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/VideoMarkers.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/GamesServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/UsersServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/VideoServiceTest.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Chatters.java

...
* Replaced a bunch of `// comments` with a `/** doc strings */` instead.
* Fixed typo (Heartstone vs Hearthstone)
Just thought this would be a bit cleaner for JavaDocs, not sure how lombok handles docs for generated setters though should be nicer regardless.

Replaced Comments with Doc Strings

---

common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
pubsub/src/main/java/com/github/twitch4j/pubsub/PubSubSubscription.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsRedemption.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsReward.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsUser.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PubSubResponsePayload.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelPointsRedemptionEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RedemptionStatusUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RewardRedeemedEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/TwitchPubSubTest.java

* https://github.com/twitch4j/twitch4j/issues/80
* Change `messageData` in `PubSubResponsePayloadMessage` to a `JsonNode` and move work of unpacking actual data to the `PubSub#onTextMessage` switch, since some PubSub response messageData fields are escaped JSON in a string, and others are objects. Expose more ObjectMapper methods in `TypeConvert` to make the conversion cleaner.
* Add supporting ChannelPoints domain objects and Helix methods.
Additional valuable improvements to PubSub were made by @turikhay in 
https://github.com/turikhay/twitch4j/tree/feature/channel_points_redemption that should probably be cherrypicked, but I feel like changing messageData to a JsonNode will make PubSub cleaner and easier to work with overall.

Feature: Channel Points redemption PubSub events

---

docs/content/getting-started/client-builder.md

The "Logging" link here is broken: https://twitch4j.gitlab.io/twitch4j/getting-started/client-builder/
Not anymore!

Fixing client-builder.md docs page to correctly point to logging.md page

---

docs/content/rest-kraken/channel-update-title.md
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java

Added method to update stream titles in TwitchKraken. While Kraken is deprecated according to Twitch, this is still the only way to update stream titles via the API, and the Trello road map they provide mentions nothing about finishing the Helix API to include things like this. 
This method is tested and working :)

Added updateTitle method to TwitchKraken

---

auth/src/main/java/com/github/twitch4j/auth/TwitchAuth.java
build.gradle
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
common/src/main/java/com/github/twitch4j/common/util/ThreadUtils.java
pubsub/build.gradle
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* https://github.com/twitch4j/twitch4j/issues/111
* Moved all threading to ScheduledThreadPoolExecutor (PubSub, Chat, ClientHelper)
* Added ScheduledThreadPoolExecutor clean up code
* Modified TwitchClientBuilder to be parent for ScheduledThreadPoolExecutor
* Added singleton ThreadPoolExecutor for all sub-modules and a class to retrieve it (only used when one not provided). See ThreadUtils
* Cleaned up some useless fields in Builder APIs
* Modified TwitchClientBuilder to work better with Chat module
* Removed requirement for instantiated TwitchAuth to register an identity provider. This prevents making unnecessary classes be garbage collected
*Fixed bug: listenForFollow not working due to a bad boolean case
* Moved TwitchPubSub to ArrayBlockingQueue from CircularFifoQueue (same as chat)
* …

Moved all threading to ScheduledThreadPoolExecutor

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

* Events from the TwitchChat module would not be dispatched to the general EventManager
* TwitchClientBuilder: Use the same event manager for TwitchChat

TwitchClientBuilder: Use the same event manager for TwitchChat

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Add user_name field to Helix Stream object
* Optimize TwitchClientHelper's StreamEventListener from O(m*n) to O(n) when handling TwitchHelix#getStreams calls

Add user_name to Helix Stream and optimize TwitchClientHelper's StreamEventListener

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* [ChannelGoLiveEvent Triggering more than once](https://github.com/twitch4j/twitch4j/issues/120)
* Don't schedule additional runnables if one of the same type is already running
* Fix bug where disableStreamEventListener removes elements from `listenForFollow` instead of `listenForGoLive`
* Properly cancel already running runnables when requested

Fix executors in TwitchClientHelper

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Fixes #126
* Change `listenForGoLive` and `listenForFollow` to track the channel id instead of the `EventChannel` object. This improves robustness of the code for situations where (a) the login does not match the display name or (b) the user has a name change
* Channel cache: when invalidating entries, don't bother checking `Cache#getIfPresent(Object)`
* Channel cache: replace manual put-if-absent pattern with atomic mapping handled by caffeine

TwitchClientHelper: Further username robustness

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java

* Fixes #126 (actually)
* Account for streams that would not be returned by the Get Streams endpoint due to offline status. This was done in a way to maintain O(n) complexity
* Add latest user name to channel cache for the sake of firing events with the most updated EventChannel object

Fix logic in stream listener to fire events when stream is offline

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsReward.java

* Fixes #123 
Note: this does *not* change the method names for the auto-generated lombok getters/setters of these fields (so I didn't bother with the annotation approach to fixing this problem... especially as other classes with similar fields did not either)

Fix boolean field names for Pubsub ChannelPointsReward

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsReward.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Extension.java

* #123 
* PubSub > ChannelPointsReward: boolean -> Boolean
* TwitchHelix > Extension: canActivate - String -> Boolean
When the field name for a boolean primitive starts with "is" there can be (de)serialization problems with Jackson. Converting to a Boolean object appears to alleviate this

Jackson POJOs: boolean primitive -> object for best compatibility

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChatModerationEvent.java

* Fixes #68 
* Create `ChatModerationAction` object
* Create `ChatModerationEvent`
* Create `TwitchPubSub#listenForModerationEvents(OAuth2Credential, String)`
* Create websocket message handler for the event

Add PubSub support for moderation actions

---

common/src/main/java/com/github/twitch4j/common/events/channel/ChannelChangeGameEvent.java
common/src/main/java/com/github/twitch4j/common/events/channel/ChannelChangeTitleEvent.java
common/src/main/java/com/github/twitch4j/common/events/channel/ChannelGoLiveEvent.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelChangeGameEvent.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelChangeTitleEvent.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelGoLiveEvent.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelGoOfflineEvent.java

* Fixes #137 
* Prefer `login` to `display_name` in EventChannel, even if out of date. (important for channels where the login differs from the display_name beyond capitalization)
* Create new stream status events that include the `Stream` object
* Deprecate the old stream status events
* Address potential thread contention issues with `startOrStopEventGenerationThread` by synchronizing and avoiding side-effects in AtomicReference updates
Progress on the `display_name` vs. `login` helix inconsistency can be tracked here: https://github.com/twitchdev/issues/issues/3

ClientHelper: Use login and Stream in events, address potential thread contention

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Deprecate `TwitchHelix#getStreamsMetadata`
Announcement can be found here: https://discuss.dev.twitch.tv/t/deprecation-of-the-helix-get-streams-metadata-endpoint/26407

chore: deprecate /streams/metadata due to twitch announcement

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java

* Add `TwitchKraken#approveAutomodMessage(String, String)`
* Add `TwitchKraken#denyAutomodMessage(String, String)`
https://discuss.dev.twitch.tv/t/allowing-others-aka-bots-to-use-twitchbot-reject/8508/2

feat: implement unofficial automod approve/deny v5 endpoints

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
common/build.gradle
common/src/main/java/com/github/twitch4j/common/config/ProxyConfig.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

* Create `ProxyConfig`
* Allow for its specification across the builders
* Use the settings in the various websockets/httpclients when supplied
While regular HTTP proxies are supported, I've only had luck with HTTPS when trying to interact with twitch's APIs. Also, SOCKS(4/5) is not supported, as the websocket library does not seem compatible with them (and in my testing they weren't even working with the modules that use OkHttpClient)

feat: implement proxy support

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
common/src/main/java/com/github/twitch4j/common/config/ProxyConfig.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* TwitchChat: Allow `baseUrl` to be set
* TwitchChat: Do not send the actual oauth password when the `baseUrl` does not correspond to twitch's official URL... unless `sendCredentialToThirdPartyHost` is set to `true`.
This adds support for development tools such as [fdgt](https://github.com/fdgt-apis/api) or even a irc-ws proxy for forwarding to twitch.
* `TwitchChat#timeout(String, String, Duration, String)` was missing a space between the target name and the duration in the command string
* [Build error](https://gitlab.com/twitch4j/twitch4j/-/jobs/631961846) from the interaction of `compileOnly` and two methods with the same name (`ProxyConfig#apply`)

feat: allow twitch chat websocket url to be configured

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ExtendSubscriptionEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubUpgradeEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/PrimeSubUpgradeEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java
common/src/main/java/com/github/twitch4j/common/enums/SubscriptionType.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SubscriptionData.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Subscription.java

* Handle multi-month sub gifts in pubsub
* Handle multi-month sub gifts in chat
* Handle `anonsubgift` & `anonsubmysterygift`
* Handle `giftpaidupgrade` & `anongiftpaidupgrade`
* Handle `primepaidupgrade`
* Handle `extendsub`
* Fix (de)serialization of `Subscription`
Announcement for multi-month gifts: https://discuss.dev.twitch.tv/t/updates-to-pubsub-messages-and-irc-for-multi-month-subscription-gifting/26873

feat: expand sub handling to include multi-month gifts, paid upgrades, extensions, and anonymous variations. also fix Subscription deserialization

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/NotificationSummary.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UpdateSummaryData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UpdateOnsiteNotificationSummaryEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/VideoPlaybackEvent.java

* Implement `video-playback` / `video-playback-by-id`
* Handle `update-summary` of `onsite-notifications`
* Allow for `timeAggregationUnit` to be specified for leaderboard events
* Add listen method for `channel-bit-events-public`

feat: implement video-playback topic, handle update-summary, allow leaderboard time spec, add another listen method

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java

* Work towards modules misbehaving if the processor has a low core count
* Instead of creating a dedicated thread in each pubsub instance, schedule a repeating task to flush the command queue (2.5 seconds between execution)
* Upon a request (e.g. LISTEN), schedule a task 50ms later for expedited flushing (& only allow one such task to be queued at a time)
* Fix some docs in the builder
* Fix incorrect field name in `VideoPlaybackData` (no deprecation as this topic is unofficial)

refactor: avoid eating a whole thread for each pubsub connection

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/flag/AutoModFlag.java
chat/src/main/java/com/github/twitch4j/chat/flag/FlagParser.java
chat/src/main/java/com/github/twitch4j/chat/flag/FlagType.java
chat/src/test/java/com/github/twitch4j/chat/flag/FlagParserTest.java

* Add `FlagType` + `AutoModFlag` + `FlagParser`
* Include lazy getter in `IRCMessageEvent` for the parsed `flags` (existing usernotice-based events that do not contain a reference to this event will require some more work to have these parsed flags accessible)
Brief summary of the tag from others who also found this: https://github.com/Chatterino/chatterino2/issues/1772

feat: add helpers for unofficial flags tag in chat messages

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageActionEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CheerEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java

* Add `flags` field to `CheerEvent` and `SubscriptionEvent`
* Add convenient helpers to `ChannelMessageEvent` and `ChannelMessageActionEvent` for grabbing the flags from the underlying `IRCMessageEvent`

feat: expand access to the unofficial flags tag in chat events

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
common/src/main/java/com/github/twitch4j/common/util/ExponentialBackoffStrategy.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* Create `ExponentialBackoffStrategy`
* Employ the class in `TwitchChat` and `TwitchPubSub`
* Bump required thread count for chat to be able to run backoffClearer alongside the command queue
* Fix unrelated bug in PubSub where upon reconnection, topics weren't actually being resubscribed to, because of the contains check in listenOnTopic (that I introduced)

feat: implement exponential backoff for websockets

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Change `getPermissionsFromTags` so that `badges` in `IRCMessageEvent` is updated
* Parse `badge-info` to get a more accurate subscription months count than available in `badges`
* Provide helper method to get tier information out of `badges`
Currently `badge-info` only provides this subscription-related info, but I added it as a field for future-proofing

feat: add sub tier & months getter in IRCMessageEvent

---

rest-kraken/build.gradle
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenBlock.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenBlockList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenBlockTransaction.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenChannel.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenClip.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenCreatedVideo.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenEmoticon.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenEmoticonSetList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenFollow.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenFollowList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenSubscriptionList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUser.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenVideo.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/util/KrakenVideoHelper.java
rest-kraken/src/test/java/kraken/endpoints/ChannelServiceTest.java
rest-kraken/src/test/java/kraken/endpoints/ClipsServiceTest.java
rest-kraken/src/test/java/kraken/endpoints/UsersServiceTest.java

* Add ability to set a higher timeout specifically for `TwitchKraken#uploadVideoPart`
* Add `getChannelEditors`
* Add `getChannelFollowers` (has some extra info compared to helix)
* Add `resetChannelStreamKey`
* Add `getClip` (has some extra info compared to helix)
* Add `getUserBlockList`
* Add `blockUser`
* Add `unblockUser`
* Add `getUserEmotes`
* Add `createVideo`
* Add `uploadVideoPart`
* Add `completeVideoUpload`
* Add `updateVideo`
* Add `deleteVideo`
* Add tests for a bunch of the new endpoints
* Create `KrakenVideoHelper` for simplifying the process of uploading videos
* Deprecate `addFollow` (available in helix now)
* Deprecate `updateTitle` (available in helix now)
* Fix java.time deserialization
* Include `total` field for `KrakenSubscriptionList`

feat: add kraken endpoints that are missing from helix

---

build.gradle
rest-helix/build.gradle
rest-kraken/build.gradle

* Maven shading problem due to overlapping resource: `META-INF/services/com.fasterxml.jackson.databind.Module`
* Update jackson dependencies to latest patch version
* Remove `jackson-datatype-jdk8`
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11.1

chore: update jackson to 2.11.1 and remove unused datatype module

---

common/src/main/java/com/github/twitch4j/common/util/MilliInstantDeserializer.java
common/src/main/java/com/github/twitch4j/common/util/NanoInstantDeserializer.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeLevelUp.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainEnd.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainStart.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/Leaderboard.java

* `Instant` fields reflecting inaccurate values in some cases
* Create `MilliInstantDeserializer` and use in hype train events
* Create `NanoInstantDeserializer` and use in leaderboard events

fix: correct nonstandard instant formats in some pubsub topics

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SubscriptionData.java

* Include semi-official `benefit_end_month` field in pubsub's `SubscriptionData`

feat: include extendsub-specific field in pubsub subscribe-events

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageActionEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CheerEvent.java

Add fields (and automatic getters) for:
* `ChannelMessageEvent` (convenience)
* `ChannelMessageActionEvent` (convenience)
* `CheerEvent` (necessity)
Extension of #163

feat: add sub months/tier getter to more chat events

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/BroadcasterLanguageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/ChannelStatesEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/EmoteOnlyEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/FollowersOnlyEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/Robot9000Event.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/SlowModeEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/roomstate/SubscribersOnlyEvent.java

* Fixes #170
* Fire the events from IRCEventHandler#onChannelState
* Fix up the event classes
On [2019-03-08](https://dev.twitch.tv/docs/change-log), `broadcaster-lang` was removed from the `ROOMSTATE` docs, so I marked the event as deprecated.

feat: fire specialized roomstate events

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MessageDeleteError.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MessageDeleteSuccess.java
common/src/main/java/com/github/twitch4j/common/util/ChatReply.java
common/src/main/java/com/github/twitch4j/common/util/EscapeUtils.java

* Fixes #173
* Add methods to `TwitchChat` to send messages with nonce/reply msg id/other arbitrary tags
* Add nonce & reply info to `ChannelMessageEvent` (currently not applicable to other events)
* Add convenient id & nonce getters to `IRCMessageEvent`
* Add `TwitchChat#delete(String, String)`

feat: add nonce and reply support to chat

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java

* Fixes #179
Implement:
* `ChannelMessageEvent#isHighlightedMessage`
* `ChannelMessageEvent#isSkipSubsModeMessage`
* `ChannelMessageEvent#getCustomRewardId`

feat: add convenience methods for chat-based redemptions

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

* Fixes #169 <sup>(nice)</sup>
* Allow bot owner id's to be specified in `TwitchClientBuilder`, `TwitchChatBuilder`, `TwitchPubSubBuilder`
* Update `TwitchUtils` to consider user id's
* Chat: `IRCMessageEvent`'s `commandPermissions` will contain `CommandPermission.OWNER` when appropriate
* PubSub: `PrivateMessageEvent`'s `permissions` will contain `CommandPermission.OWNER` when appropriate

feat: allow owner designation via builder and CommandPermission

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenIngestList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenSubscriptionList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenTeamList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUserList.java

Running into `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "_total" (class com.github.twitch4j.kraken.domain.KrakenUserList), not marked as ignorable (one known property: "users"])` after updating to `1.1.1` - I would guess that [switching to our own ObjectMapper](https://github.com/twitch4j/twitch4j/commit/dc2d3773b678a293d35eba7b58db2009ca19232c#diff-74d77f21f2c1932bbe4611b84d52acfaR97) had a different default configuration than what was used by feign.
Add `JsonIgnoreProperties` to a few classes to avoid this error

fix: ignore missing properties in kraken result lists

---

common/src/main/java/com/github/twitch4j/common/util/ExponentialBackoffStrategy.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Use `ExponentialBackoffStrategy` in `TwitchClientHelper`
* Rework threading so that delays between tasks can be adjusted on the fly without using Thread#sleep

feat: new thread approach in client helper with exp backoff

---

common/src/main/java/com/github/twitch4j/common/util/TimeUtils.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelPointsRedemptionEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RedemptionStatusUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RewardRedeemedEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AnaylticsDateRange.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Follow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Moderator.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorEventList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/VideoMarker.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenTeam.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenTeamUser.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUser.java
rest-kraken/src/test/java/kraken/endpoints/UsersServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java

* Work towards #61
* `TwitchHelix#getClips`: passing a `Date` (for `startedAt` or `endedAt`) would always result in failure due to its `toString` method not yielding a RFC 3339 compliant format
* `LocalDateTime`, `Date`, `Calendar` => `Instant`
* Improve documentation of `Moderator` and `ModeratorEvent`
* Rename `subscriptions` field in `ModeratorList` and `ModeratorEventList`

refactor: modernize timestamps, rename fields, improve javadocs

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionTransaction.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionTransactionList.java

`ExtensionTransactionList`: Deserialization of `pagination` field would fail due to expecting a `String` while encountering a json object
* Change type of `pagination` field to `HelixPagination`
* Tabs => 4 spaces
https://dev.twitch.tv/docs/api/reference#get-extension-transactions

fix: deserialize pagination in extension transaction list

---

rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java

* the tmi module had the loglevel forced to BASIC and wasn't using slf4j for logging
* allow overwriting the loglevel in all feign builders
* set the default loglevel to `NONE`
* delegate all logging to slf4j

fix: feign request + response logging

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUser.java
rest-kraken/src/test/java/kraken/endpoints/ChannelServiceTest.java
rest-kraken/src/test/java/kraken/endpoints/UsersServiceTest.java

* Add `TwitchKraken#getChannelTeams(String)` - no analog in helix yet
* Add `TwitchKraken#getUser(String)` - has some fields not present in helix
* Add `TwitchKraken#getUserById(String)` - has some fields not present in helix

feat: add kraken getChannelTeams + getUser + getUserById

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/DropsEntitlement.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/DropsEntitlementList.java

* Implement `TwitchHelix#getDropsEntitlements(String, String, String, String, String, Integer)`
https://dev.twitch.tv/docs/api/reference#get-drops-entitlements (was added under a month ago to the API)

feat: add get drops entitlements endpoint to helix

---

docs/content/rest-helix/streams-get.md
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Could only previously request a single language because the field was a `String` instead of `List<String>` and the query parms need to be repeated (since feign will not allow `;` to be used in a single string to split up the languages as it must encode it to `%3B`)
* Create new getStreams method that changes `String language` to `List<String> language` (also we remove `communityId` as it is no longer supported by twitch)
* Deprecate old getStreams method (and point it to the new one)
Endpoint: https://dev.twitch.tv/docs/api/reference#get-streams
Changelog: https://dev.twitch.tv/docs/change-log
> 9/10/2019: Removed communities-related data fields from Get Streams and Get Streams Metadata endpoints. These fields are no longer supported.

fix: allow multiple languages to be specified in helix getStreams

---

docs/content/pubsub/topic-bits-badge-unlocks.md
docs/content/pubsub/topic-bits-events.md
docs/content/pubsub/topic-commerce-events.md
docs/content/pubsub/topic-moderation-events.md
docs/content/pubsub/topic-subscribe-events.md
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* Confusion regarding argument ordering of `TwitchPubSub#listenForModerationEvents(OAuth2Credential, String, String)`
* Change "user id" to "channel id" where appropriate in javadocs
* Reflect above changes in markdown docs as well
* Extraneous: change nonce length to 30 instead of 32 to match twitch's first-party clients
* Extraneous: add listen method for unofficial `user-drop-events` topic & mark it deprecated (as there is no implementation provided yet)

docs: improve clarity of channel ids in pubsub

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ActiveExtension.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Extension.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionActiveList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionList.java

* Create `ActiveExtension` object that is distinct from a regular `Extension`; fields are slightly different so `TwitchHelix#getUserActiveExtensions` yields more information now
* Ease creation of `ExtensionActiveList`/`ActiveExtensions`/`ActiveExtension`; this makes `TwitchHelix#updateUserExtensions` more powerful
* Deprecate pagination fields in helix extension lists; not relevant for these endpoints
* Remove some unnecessary annotations

feat: improve utility of active extensions in helix

---

rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensions.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ExtensionInformation.java

* Continuing #171
* Add `TwitchExtensions#getExtensionInformation(String)`

feat: add unofficial get extension information endpoint

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Commercial.java

* Apply `SnakeCaseStrategy` so jackson looks for `retry_after` instead of `retryAfter`
* On [6/18](https://discuss.dev.twitch.tv/t/announcing-the-latest-helix-endpoints-and-hype-train-api/26530), the "Start Commercial" endpoint was released (with the docs claiming this field name is `retryAfter`)
* On [6/19](https://github.com/twitch4j/twitch4j/pull/144), we implemented this endpoint as documented
* On [7/30](https://dev.twitch.tv/docs/change-log), twitch updated the documentation to change `retryAfter` to `retry_after`

fix: deserialize retry_after in helix commercial properly

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java

* will ensure that channel id + name are present in all events
* adds 2 maps to store the mapping (channel id -> name, channel name -> id) for all joined channels)

feat: provide channel id + name in all events

---

CODE_OF_CONDUCT.md
README.md

* Adopt Contributor Covenant Code of Conduct version 1.4
* Add section on contributing to README
* Add line to modules section in README indicating Extensions API support

docs: add code of conduct and link contributing guide in readme

---

rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Chatters.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Host.java

* Add `host_partnered` field to `Host` (can appear when doing `getHostsOf`)
* Add `display_name` fields to `Host` (always present in  `getHosts`, only present for the person hosting when doing `getHostsOf`)
* Add `broadcaster` field to `Chatters` - indicates whether the broadcaster is in chat or not
* Deprecate staff-related fields in `Chatters` - twitch decided to stop sending this info (it's always an empty array now)

feat: add more host and chatter info to tmi

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

* makes sure the language param is omitted in the deprecated helix.getStreams request if its not set
* allows setting the feignLogLevel globally in the twitchClientBuilder

fix: deprecated helix.getStreams issue with language param

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioTrack.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RadioEvent.java

* Handle `radio-events-v1.<channel-id>` unofficial pubsub topic
Related announcement: https://blog.twitch.tv/en/2020/09/30/introducing-soundtrack-by-twitch-rights-cleared-music-for-all-twitch-creators/

feat: handle unofficial radio events pubsub topic

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreatedUnbanRequest.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UnbanRequest.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UpdatedUnbanRequest.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelUnbanRequestCreateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelUnbanRequestUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UnbanRequestEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserUnbanRequestUpdateEvent.java

* Handle unofficial `channel-unban-requests.<user-id>.<channel-id>` pubsub topic (for mods to receive unban request creations and updates in real-time)
* Handle unofficial `user-unban-requests.<user-id>.<channel-id>` pubsub topic (for banned users to monitor the status of their unban request)

feat: handle unban request pubsub topic for channels and users

---

build.gradle
common/build.gradle
common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
rest-helix/build.gradle
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CategorySearchList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceErrorDecoder.java

* Folks using Twitch4J in minecraft server plugins would have issues when `Instant`s needed to be deserialized from JSON, despite properly shading their plugin jar to include jackson and the jsr310 module. The custom [PluginClassLoader](https://papermc.io/javadocs/paper/1.13/org/bukkit/plugin/java/PluginClassLoader.html) used in this context likely is not compatible with `ObjectMapper#findAndRegisterModules`
* Explicitly register `ParameterNamesModule` and `JavaTimeModule` (so we are also shifting off of the deprecated `JSR310Module` with this PR) in `TypeConvert`, instead of relying upon `findAndRegisterModules`
* Use `TypeConvert`'s `ObjectMapper` wherever possible
* Bump jackson version
* Bump caffeine version
* Bump JUnit version
* Fix typo in pagination of hype train events caused by …

fix: register jackson modules despite exotic class loaders

---

docs/content/rest-tmi/_index.md
docs/content/rest-tmi/get-chatters.md
docs/content/rest-tmi/get-hosts-of.md
docs/content/rest-tmi/get-hosts.md

* [Issue #205]
Added markdown docs for get-hosts and get-hosts-of, renamed get-viewers, and added `Chatters#getBroadcaster` example.

docs: add missing TMI docs and rename get-viewers

---

docs/content/rest-helix/_index.md
docs/content/rest-helix/moderators-get-events.md
docs/content/rest-helix/moderators-get.md
docs/content/rest-helix/streams-get-key.md

* [Issue #203]
Added markdown docs for Helix endpoints `getModerators`, `getModeratorEvents`, and `getStreamKey`.

docs: add moderators and getStreamKey Helix docs

---

.gitignore
build.gradle
deployment.gradle

- adding 'io.freefair.lombok' version '5.2.1'
- append all javadocs source to delombok task - [reference](https://docs.freefair.io/gradle-plugins/5.2.1/reference/#_io_freefair_lombok)
- ignores auto-generate 'lombok.config' for each existed project
- adding 'aggregateJavadoc' to generate combined javadoc for new incoming website
@iProdigy request it and he have it. Feel free to checking changes. Also i've added new task which he generate whole project aggregate into one javadoc. For new website purpose (soon™️). Here is diffrence between non-delomboked and delomboked files:

docs: javadoc aggregation and delombok

---

common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
pubsub/build.gradle
pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/Prediction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PredictionColor.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PredictionEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PredictionOutcome.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PredictionResult.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PredictionTrigger.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PredictionCreatedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PredictionUpdatedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserPredictionMadeEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserPredictionResultEvent.java

* Implement `predictions-channel-v1` unofficial pubsub topic
* Implement `predictions-user-v1` unofficial pubsub topic
* Implement `CommandPermission.PREDICTIONS_BLUE` and `CommandPermission.PREDICTIONS_PINK`
https://blog.twitch.tv/en/2020/12/12/channel-points-predictions-let-your-viewers-guess-your-destiny/

feat: add channel point predictions pubsub and badge

---

build.gradle
deployment.gradle

1. Apply plugin `com.github.johnrengelman.shadow` - Closes #226 
In #226 where providing this plugin and applying `shaded` word into `archiveClassifier` for `shadowJar` task, will automatically adds into `MavenPublication`. 
All those changes are be tested before the pull request.

build: shadow jar - all deps in one jar

---

graphql/build.gradle
graphql/src/main/java/com/github/twitch4j/graphql/command/BaseCommand.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFollowUser.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandUnfollowUser.java

Dependabot failures:
* Closes #241 
* Closes #242 
* Bump `apollo-runtime` to 2.4.6
* Utilize `com.apollographql.apollo` plugin rather than legacy buildscript approach
* Improve performance of `BaseCommand#run` via `java.util.concurrent`
* Include generic parameter in `BaseCommand#getGraphQLCall` for clarity

chore: bump apollo graphql to 2.4.6

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ApplicationEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/CustomRewardEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/EventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/UserEventSubCondition.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/util/EventSubConditionConverterTest.java

* Remove `EventSubCondition#toMap`
After changing helix to depend on eventsub-common, `EventSubCondition#toMap` was no longer needed.

refactor: remove obsolete EventSubCondition#toMap

---

common/src/main/java/com/github/twitch4j/common/config/Twitch4JGlobal.java
common/src/main/java/com/github/twitch4j/common/feign/interceptor/JsonContentTypeHeaderInterceptor.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java

* adds a interceptor for kraken api requests that:
* - sets the accept header `application/vnd.twitchtv.v5+json` for all requests
* - sets the content-type header for PUT,PATCH,POST requests if not set in the TwitchKraken interface
* bumps the t4j user-agent to Twitch4j/1.2.0 (next release version)

refactor: set default kraken headers (accept, content-type) using interceptor

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubNotification.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/util/NotificationDeserializer.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/EventSubNotificationTest.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Include `challenge` field in `EventSubNotification`
* Remove twitch documentation error regarding api access to manually created rewards

feat: include challenge in EventSubNotification

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java

* `VideoPlaybackData.Type` *does* need the custom `@JsonCreator`

fix: properly deserialize video playback type

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/FollowEvent.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

Instead of simple `void` functions, these enable methods now provide the `User` on success (which is useful for caching properties like the profile image url to be used in discord embeds)
* `enableStreamEventListener(String) => User`
* `enableStreamEventListener(Iterable<String>) => Collection<User>`
* `enableFollowEventListener(String) => User`
* `enableFollowEventListener(Iterable<String>) => Collection<User>`
Also:
* Removed 10k limit on `channelInformation`
* Include channel info in `FollowEvent#toString`
* Don't invalidate entries in `channelInformation` cache if the channel was removed from one event listener but is still relevant for the other event listener

refactor: yield user on enable client helper event listener

---

build.gradle
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelFollowEvent.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/EventSubNotificationTest.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Include new `followedAt` field in `ChannelFollowEvent`
* Update TwitchHelix javadoc to include new `channel:manage:broadcast` scope
* Bump credential manager version

feat: include timestamp in eventsub follow event

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelFromToEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelRaidCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelRaidEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubChannelFromToEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelRaidType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Include `channel.raid` *beta* eventsub type/condition/event
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelraid-beta

feat: include channel raid beta eventsub type

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/StreamOnlineEvent.java

* Include `started_at` in `StreamOnlineEvent`
https://dev.twitch.tv/docs/eventsub/eventsub-reference#stream-online-event

feat: include new started_at field for eventsub StreamOnlineEvent

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscription.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelBanEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUnbanEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubModerationEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsCustomRewardAddType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsCustomRewardRedemptionAddType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsCustomRewardRedemptionUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsCustomRewardRemoveType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsCustomRewardUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/util/EventSubVerifier.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* EventSub Channel Ban v1 now includes moderator information, reason for ban, and timeout duration if the ban was a timeout.
* EventSub Channel Unban v1 now includes moderator information.
* In EventSub, the authorization scopes allowed for all Channel Point subscription types have been updated to accept channel:read:redemptions or channel:manage:redemptions.

feat: update eventsub with february changes

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenHost.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenHostList.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java

* `TwitchMessagingInterface#getHostsOf(String)` is no longer working
* Add `TwitchKraken#getHostsOf(String)`

feat: add unofficial kraken hosts endpoint

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/DropsEntitlementList.java

* https://github.com/twitchdev/issues/issues/340
* Convert `DropsEntitlementList` `pagination` field type from `Object` to `HelixPagination`
* `The maximum value for the number of items return via the first parameter has been increased to 1000.`

refactor: remove drops entitlement pagination workaround for docs issue

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Subscription.java

* `BannedEvent` & `Subscription` are no longer missing new `login` fields

refactor: include even more helix response login fields

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java

* Add `ITwitchChat#sendMessage(String, String, String, String)` so chat connection pools can use the unofficial nonce & reply feature
* Add `ITwitchChat#getChannelIdToChannelName` and `ITwitchChat#getChannelNameToChannelId` (requested by a discord user)

feat: add sendMessage with nonce or reply to ITwitchChat

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelViewerCountUpdateEvent.java

* Create `ChannelViewerCountUpdateEvent` & fire from client helper
* Create `TwitchClientHelper#getCachedInformation(String)` (has been requested a few times on discord)

feat: add viewer event to client helper and channel cache getter

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* https://cdn.discordapp.com/attachments/268348117919858688/833003511150805002/7f416530a57784ffc85aed8d2effe5ad.png
* Reset last ping to avoid edge case loop where reconnect occurred after sending PING but before receiving PONG

fix: resolve pubsub reconnect loop from ping edge case

---

common/src/main/java/com/github/twitch4j/common/enums/SubscriptionType.java

* Add `EXTEND_SUB` to `SubscriptionType`

fix: include extendsub in SubscriptionType to avoid null context in pubsub

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java

* topic name correction: `sub-gift-sent` should be `sub-gifts-sent`

fix: correct unofficial subgift leaderboard pubsub topic name

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Add `CommandPermission.BITS_CHEERER` (and associated parsing logic in `TwitchUtils`)
* Add `IRCMessageEvent#getCheererTier` (I'm not in love with this method name so we can change it if you have any ideas)
* Ensure `CommandPermission.PRIME_TURBO` is present for turbo users
* Small code formatting changes in `TwitchUtils`

feat: add cheer badge to chat permissions

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java

* Deprecate `TwitchKraken#getHostsOf(String)`
`{"error":"Gone","status":410,"message":"Endpoint has been decommissioned"}`

chore: kraken hosts was decommissioned by twitch

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GlobalUserStateEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java

* Previously, `GLOBALUSERSTATE` would yield `UNKNOWN` for `commandType` so no event would be fired https://discord.com/channels/143001431388061696/760173135021604914/805985982854987816
* Fix: `MESSAGE_PATTERN`: make the space following the command group optional (`GLOBALUSERSTATE` has no such space)
* Refactor: `MESSAGE_PATTERN` & `WHISPER_PATTERN`: remove unnecessary non-capturing group, unnecessary escape character, convert space characters to `\s`
* New: fire `GlobalUserStateEvent` from `IRCEventHandler` for convenience
`GLOBALUSERSTATE` is useful for confirming one has logged into chat https://discord.com/channels/143001431388061696/268348117919858688/805966340736548864

feat: fire global user state chat event

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Implement `TwitchHelix#getFollowedStreams(String, String, Integer, String)`
* Add `TwitchScopes.HELIX_USER_FOLLOWS_READ`
https://dev.twitch.tv/docs/api/reference/#get-followed-streams

feat: add new get followed streams helix endpoint

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubscriptionsEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Parse `msg-param-multimonth-duration` & `msg-param-multimonth-tenure` for `SubscriptionEvent` (unofficial)
* Handle `bits-leader` in the same way as `bits` for permissions

feat: add unofficial multi month chat tags

---

rest-helix/build.gradle
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixClientIdInterceptor.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixHttpClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java

* Track api bucket point usage of the user/app access token(s) in `TwitchHelixClientIdInterceptor`
* Create a custom `JacksonDecoder` to track ratelimit headers received by twitch to ensure our bucket cache is in harmony
* Delegate http calls in `TwitchHelixHttpClient` immediately or with delay, depending on the amount of points left in the corresponding bucket

feat: automatically handle helix rate limits

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

* User complaint about repeated warnings in logs: `WARN  com.github.twitch4j.chat.TwitchChat - Already joined channel <insert bot name>` https://discord.com/channels/143001431388061696/551499165646192650/839195881840181311
* On connect, for the autoJoinOwnChannel logic, check whether the channel is already joined first
This issue had no side effects other than the logs annoyance (i.e., a second JOIN wasn't being sent over the socket)

refactor: avoid double join of own channel on reconnect

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessageData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodContentClassification.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/AutomodCaughtMessageEvent.java

* Implement `automod-queue.<user-id>.<channel-id>` unofficial pubsub topic to track automod acting against messages in chat
https://github.com/Chatterino/chatterino2/issues/2682#issuecomment-831495637

feat: implement unofficial automod-queue pubsub topic

---

build.gradle.kts

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by feign.DefaultMethodHandler (file:/C:/Users/User/.m2/repository/io/github/openfeign/feign-core/11.0/feign-core-11.0.jar) to field java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP
WARNING: Please consider reporting this to the maintainers of feign.DefaultMethodHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
* Bump `feign` dependencies to 11.2

chore: bump openfeign from 11.1 to 11.2

---

.ci/env
.github/workflows/gradle-wrapper.yml

This will add the first workflow from #229, to schedule a update of the gradle wrapper.
The action will create a MR for each update and runs against develop, it's possible to manually trigger the workflow.

chore: workflow - gradle update from #229

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutoModHeldMessageAction.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java

* `TwitchKraken#approveAutomodMessage` & `TwitchKraken#denyAutomodMessage` are being decommissioned tomorrow
* Implement `TwitchHelix#manageAutoModHeldMessage(String, String, String, AutoModHeldMessageAction)`
<https://dev.twitch.tv/docs/api/reference#manage-held-automod-messages>

feat: implement helix manage held automod message endpoint

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelTermsAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelTermsEvent.java

* Twitch made an undocumented change to this topic where the old parsing system would not properly handle add/remove blocked/permitted terms actions
* Handle messages under `channel_terms_action` via `ChannelTermsEvent`
* For `moderation_action`, include `chat_targeted_login_moderation` under `ModerationType.LOGIN`
* Include `automod_message_rejected`, `automod_message_approved`, & `automod_message_denied` in `ModerationAction` enum
https://github.com/Chatterino/chatterino2/issues/2682#issuecomment-831495637
https://github.com/Chatterino/chatterino2/issues/2626#issuecomment-831548361

fix: handle new channel terms changes under moderator pubsub

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPredictionEndEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPredictionLockEvent.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

This covers the changes deployed to eventsub today:
- The eventsub channel.prediction.lock payload has a locked_at timestamp, rather than locks_at
- The eventsub channel.prediction.end payload has had its locked_at field removed due to edge cases around predictions that were cancelled or resolved prematurely
See https://discord.com/channels/504015559252377601/776875921654546463/842867470343864351

fix: remove lockedAt in predictionEnd / rename locksAt to lockedAt in predictionLock

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java

* Twitch Docs for this field were wrong so `ChannelSearchResult.tagsIds` was not being written to: https://github.com/twitchdev/issues/issues/394
* Correct the json property name for tag id's in `ChannelSearchResult`

fix: properly deserialize tag ids from searchChannels

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/EventSubSubscriptionList.java

Update javadocs for [changes made on 2021-05-14](https://dev.twitch.tv/docs/change-log)
* Get Channel Information; Added `delay` to return values
* Get/Create EventSub Subscriptions: `limit` removed

docs: note that delay is now included in getChannelInformation

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/InboundHostEvent.java

* Create & fire `InboundHostEvent`

feat: fire chat event for hosts of own channel

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ModeratorUnbanRequestAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ModUnbanRequestActionEvent.java

* `approve_unban_request` & `deny_unban_request` would yield the unparsable message warning
* Add branch and models (e.g., `ModeratorUnbanRequestAction`) to properly handle this case

feat: handle approve deny unban request within chat_moderator_actions pubsub

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPollBeginEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPollEndEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPollEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPollProgressEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PollBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PollEndType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PollProgressType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PredictionBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PredictionEndType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PredictionLockType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/PredictionProgressType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Remove beta warnings in TwitchHelix
* Replace beta eventsub models with v1
2021‑05‑24 <https://dev.twitch.tv/docs/change-log>

chore: promote polls predictions api from beta to v1

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* `[4:responseBody={"error":"Bad Request","status":400,"message":"Missing required parameter \"broadcaster_id\""}]`
* Remember to pass the query params to the url for `TwitchHelix#updateRedemptionStatus`
Thanks to Jilence#0001 for reporting

fix: pass query params to url for updateRedemptionStatus

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessageData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodContentClassification.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UserAutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/AutomodCaughtMessageEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserAutomodCaughtMessageEvent.java

* Implement official `user-moderation-notifications.<user-id>.<channel-id>`  pubsub topic
Depends on #331

feat: handle official user-moderation-notifications pubsub topic

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadge.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadgeSet.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadgeSetList.java

* Implement `TwitchHelix#getChannelChatBadges(String, String)`
* Implement `TwitchHelix#getGlobalChatBadges(String)`
Added on 2021‑05‑28: <https://dev.twitch.tv/docs/change-log>

feat: implement new chat badges helix api

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/util/ChatCrowdChant.java
pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CrowdChant.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/CrowdChantCreatedEvent.java

* Implement unofficial `crowd-chant-channel-v1.<channel-id>` pubsub topic
* Parse crowd chant info in ChannelMessageEvent (and allow chant participation via `ChatCrowdChant#participate(TwitchChat)`)
https://twitter.com/TwitchSupport/status/1394684445001752578

feat: support crowd chant chat and pubsub experiment

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodContentClassification.java

* Add undocumented `link` field to `AutomodCaughtMessage.Fragment`
* Add undocumented `user_mention` field to `AutomodCaughtMessage.Fragment`
* Throw more aliases into `AutomodContentClassification.Category` (some of which are observed while most are guesses)
* Undeprecate `AutomodContentClassification.Category#IDENTITY` (this *is* actually still sent over the socket in some cases)

feat: include unofficial fields in AutomodCaughtMessage.Fragment

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/SubscriptionList.java

* Include `total` in `SubscriptionList`
2021-06-02: Get Broadcaster Subscriptions - total subscription count added to the response. <https://dev.twitch.tv/docs/change-log>

feat: include new total field in helix SubscriptionList

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Predictor.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelSubscriptionGiftEvent.java

* Add `ChannelSubscriptionGiftEvent#isAnonymous`
* Add some aliases for properties in `Predictor` due to [twitch docs inconsistency](https://twitch.uservoice.com/forums/310213-developers/suggestions/43521057-incorrect-documentation-for-predictions)
`Channel Subscription Gift EventSub subscription type - Added is_anonymous boolean to the event.` <https://dev.twitch.tv/docs/change-log>

feat: add isAnonymous field to eventsub subgift event

---

chat/src/main/java/com/github/twitch4j/chat/enums/NoticeTag.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelNoticeEvent.java

* Create `NoticeTag` enum and parse `ChannelNoticeEvent#msgId` into the enum
https://dev.twitch.tv/docs/irc/msg-id

feat: parse notice msgId to convenient enum

---

rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/util/TwitchExtensionsErrorDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceErrorDecoder.java

* prevents printing auth tokens into the log on api request errors
* warning about sharing logs when full-request logging is enabled as they contain the auth headers

chore: warn on full request logging / keep api auth tokens out of logfiles

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java

* Closes #390 
Loosen our thread pool naming pattern matching so that the following are recognized as twitch4j threadpools that ought to be shutdown on close:
* `"twitch4j"`
* `"twitch4j-" + RandomStringUtils.random(4, true, true)`
* `"twitch4j-chat-" + RandomStringUtils.random(4, true, true)`
* `"twitch4j-pubsub-" + RandomStringUtils.random(4, true, true)`
* `"twitch4j-pool-" + RandomStringUtils.random(4, true, true) + "-chat-" + RandomStringUtils.random(4, true, true)`
* `"twitch4j-pool-" + RandomStringUtils.random(4, true, true) + "-pubsub-" + RandomStringUtils.random(4, true, true)`

fix: properly shutdown twitch4j thread pools on close

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUnsubscribeEvent.java

* EventSub: Add `tier` and `is_gift` fields to Channel Subscription End Event

feat: add new fields to eventsub channel unsub event

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodContentClassification.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelBitsData.java

* Following up on https://github.com/twitch4j/twitch4j/pull/332#discussion_r637615212
* Use `String#split` on the topic to identify parts instead of utilizing startsWith/(last)indexOf
* Avoid writing `auth_token` to debug log on `LISTEN`
* Fix javadoc generation of `AutomodContentClassification.Category`
* Add `is_anonymous` field to ChannelBitsData

refactor: improve pubsub topic name matching

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java

* Inbound host messages now have the suffix `is now hosting you for up to %d viewers.` so the current approach would stop firing the event
* Fire `InboundHostEvent` again by loosening the string matching

fix: update InboundHostEvent with latest twitch pattern

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java

* Mark create/delete follow endpoints as deprecated as they will be shutdown in a couple of days
https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351

chore: deprecate create and delete follow endpoints

---

common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduleSegmentInput.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduledSegment.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduledVacation.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamSchedule.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamScheduleResponse.java

* Add `TwitchHelix#getChannelStreamSchedule`
* Add `TwitchHelix#getChannelInternetCalendar`
* Add `TwitchHelix#updateChannelStreamSchedule`
* Add `TwitchHelix#createStreamScheduleSegment`
* Add `TwitchHelix#updateStreamScheduleSegment`
* Add `TwitchHelix#deleteStreamScheduleSegment`

feat: implement new helix schedule api

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUser.java

* `BannedEvent` and `BannedUser` now include `reason`, `moderatorId`, `moderatorLogin`, `moderatorName` fields

feat: add new fields to helix banned routes

---

build.gradle.kts

* resolves `Could not find com.fasterxml.jackson.datatype:jackson-datatype-jsr310:.`, see below.
Issue was reported via discord, the jackson bom wasn't available in the compile classpath because of `implementation` and as such it used feign-jackson to resolve the databind version, but couldn't resolve jsr310.
```
i've ran into the same jackson-datatype-jsr310 dependency issue with gradle and twitch4j 1.5.0.
This can be reproduced with a simple build.gradle:
plugins {
id 'java'
}
group = 'com.example'
version = '1.0'
sourceCompatibility = '1.8'
repositories {
mavenCentral()
}
dependencies {
api 'com.github.twitch4j:twitch4j:1.5.0'
}
and something to compile (src/main/java/com/example/Main.java):
package com.example;
public class Main {
public static void main(String[] args) { …
```

fix: jackson bom -> api

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/WebhookSubscription.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/WebhookSubscriptionList.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/domain/WebhookNotification.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/domain/WebhookRequest.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ChannelBanTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ChannelSubscriptionTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ExtensionTransactionsTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/FollowsTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/HypeTrainTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ModeratorChangeTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/StreamsTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/TwitchWebhookTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/UsersTopic.java

* Deprecate WebSub
https://discuss.dev.twitch.tv/t/deprecation-of-websub-based-webhooks/32152

chore: deprecate helix webhooks due to twitch announcement

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelSubscriptionMessageCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Message.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelSubscriptionMessageEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUnsubscribeEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelSubscriptionMessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelSubscriptionGiftType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelSubscriptionMessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* https://github.com/twitchdev/issues/issues/415
* Implement Channel Subscription Message (v1) EventSub
* Promote Channel Subscription Gift EventSub from beta to v1
* Add `tier` and `is_gift` fields to Channel Subscription End Event
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsubscriptionmessage

feat: implement channel.subscription.message v1 eventsub

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommerceMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SubGiftData.java

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "emotesv2_01ad668a984f449ba9d950381638056a": not a valid `int` value
```
* Make the emote id in pubsub commerce messages a string (in unbreaking fashion)
* Unrelated: add more fields for unofficial sub gift events over pubsub
Thanks to `Doc#4444` for reporting

fix: store emote id as string in sub events over pubsub

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainConductorUser.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainConfig.java

* `HypeTrainConductorUser` and `HypeTrainConfig` now are sent with more info by twitch

feat: add more unofficial fields for pubsub hype trains

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Emote.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/EmoteList.java

* Add template url to emote list
* Add fields to populate the template with to the emote objects themselves
https://discuss.dev.twitch.tv/t/twitch-emotes-api-endpoints-now-include-an-image-template-string-and-image-options/33069

feat: support new emote api url template fields

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java

* Closes #431 
* Fire `ChatModerationEvent` for alternative message format of `mod`/`unmod`/`vip`/`unvip`
More details: https://github.com/twitchdev/issues/issues/218#issuecomment-922212618
* There are scenarios where no pubsub message is sent when we would expect one
* There are scenarios where `ChatModerationEvent` will be fired more than once (because twitch can send both the traditional format and this new format)

fix: parse new mod pubsub format for mod and vip actions

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageActionEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CheerEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ReplyableEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java
common/src/main/java/com/github/twitch4j/common/util/ChatReply.java

* Closes #245 
* Create `ReplyableEvent` interface (to simply sending a chat reply) & implement it for `ChannelMessageEvent`, `ChannelMessageActionEvent`, `CheerEvent`, and `SubscriptionEvent`

feat: add convenient reply method to chat events

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/CustomReward.java

* Was not able to create/update custom rewards' setting objects (i.e., `max_per_stream_setting`, `max_per_user_per_stream_setting`, and `global_cooldown_setting`) easily. Thanks to `vojay#0001` for reporting.
* Add `@SuperBuilder` to these setting objects
Went with `@SuperBuilder` to properly work with inheritance (e.g., `@With` & `@AllArgsConstructor` alone were problematic) and avoid modifying internal state (e.g., `@Setter(AccessLevel.PUBLIC)`).

feat: add builder to modify custom reward setting objects

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/SubscriptionList.java

* Add `SubscriptionList#getPoints`
2021-10-01: `Add the points field to the Get Broadcaster Subscriptions response. This field provides the current number of subscriber points earned by this broadcaster.` https://dev.twitch.tv/docs/change-log

feat: add new points field to SubscriptionList

---

chat/src/main/java/com/github/twitch4j/chat/enums/NoticeTag.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java

* Add unofficial chat verification notice tags
* Add unofficial vip chat notice tags
* Refactor `IRCEventHandler` to utilize `NoticeTag` (and fire `MessageDeleteError` event in more cases)
Thanks to Alca and Syzuna for message samples with the new verification notices
VIP notice info: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848266-msg-id-tags-page-outdated-incorrect

feat: add unofficial notice tags for vips and channel verification settings

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java

* Add `Clip#getBroadcasterName`
* Add `Clip#getCreatorName`
Was added at some point to [Get Clips](https://dev.twitch.tv/docs/api/reference#get-clips) without an entry on the official [changelog](https://dev.twitch.tv/docs/change-log)

feat: add broadcaster and creator names to Clip object

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/util/TwitchChatLimitHelper.java
common/build.gradle.kts
common/src/main/java/com/github/twitch4j/common/enums/TwitchLimitType.java
common/src/main/java/com/github/twitch4j/common/util/TwitchLimitRegistry.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Create `TwitchLimitRegistry` for people to specify elevated rate-limit bandwidths for specific user id's
* Ensure chat message/join/whisper default limit can be configured in each relevant builder
* In TwitchChatBuilder, obtain the shared rate-limit buckets from `TwitchLimitRegistry`
Recently twitch actually started enforcing it's irc JOIN ratelimit (rather strictly). As a result, there has been more demand to be able to easily override the default non-message ratelimits (e.g., to set a lower limit than the default to avoid network oddities making it appear that a small ratelimit violation occurred from twitch's perspective). Also, the bot verification process has started again so more folks may want to easily specify their updated ratelimits.

refactor: allow chat limit specification in more builders

---

graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchActivePredictions.graphql
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchBanStatus.graphql
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchChatHistory.graphql
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchChatters.graphql
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchLockedPredictions.graphql
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchActivePredictions.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchBanStatus.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchChatHistory.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchChatters.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchLockedPredictions.java
graphql/src/test/java/com/github/twitch4j/graphql/TwitchGraphQLTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Implement `fetchBanStatus`, `fetchChatHistory`, `fetchChatters`, `fetchActivePredictions`, `fetchLockedPredictions`
* Properly apply `timeout`
* Add `defaultFirstPartyToken` to `TwitchClientPoolBuilder`
Previously, `timeoutInMilliseconds` was set to `1000` by default

feat: add more chat and prediction related gql queries

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java

`ChatModerationAction(type=chat_channel_moderation, moderationAction=null, args=null, createdBy=beatz41, createdByUserId=239088839, msgId=, targetUserId=, targetUserLogin=, fromAutomod=false, modType=CHANNEL)`
* Add `CLEAR` to `ChatModerationAction.ModerationAction`
Thanks to @beatzzz for reporting

fix: add clear chat mod action to pubsub topic

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/ModerationServiceTest.java

* Deprecate `TwitchHelix#getBannedEvents`
* Deprecate `TwitchHelix#getModeratorEvents`
* Deprecate `TwitchHelix#getSubscriptionEvents`
https://discuss.dev.twitch.tv/t/deprecation-of-twitch-api-event-endpoints-that-supported-websub-based-webhooks/35137

chore: deprecate helix get banned,moderator,subscription events

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/BanUsersInput.java

* Avoid Stream API overhead and some unnecessary object creation in constructors of `BanUsersInput` that accept user id's (which can be helpful for executing very large ban lists)
* `List<String> userIds` => `Collection<String> userIds` so more data structures can be accepted (e.g. `Set<String>`)

perf: optimize user id to ban user input mapping

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackAlbum.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackArtist.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrack.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrackWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistMetadataList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistTracks.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistTracksWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackSource.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackTrack.java

* Add `TwitchHelix#getSoundtrackCurrentTrack`
* Add `TwitchHelix#getSoundtrackPlaylist`
* Add `TwitchHelix#getSoundtrackPlaylists`
Added on [2021-12-09](https://dev.twitch.tv/docs/change-log)

feat: implement soundtrack beta helix endpoints

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* For the very first follower of a channel (follow count goes from 0 to 1), `ChannelFollowCountUpdateEvent` will fire but a corresponding `FollowEvent` may not
* Minor adjustment to `lastFollowDate` logic in `TwitchClientHelper` so that `follow.getFollowedAtInstant().isAfter(currentChannelCache.getLastFollowCheck())` does not evaluate to false for the very first follower
Thanks to @DenalidTX for reporting

fix: ensure first ever follower triggers FollowEvent

---

auth/build.gradle.kts
build.gradle.kts
twitch4j/build.gradle.kts

* adds a rich version constraint for jackson databind (require 2.12.0+, prefer 2.13.0)
Docs: https://docs.gradle.org/current/userguide/rich_versions.html

chore(deps): add a rich version constraint for databind 2.13.0

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java

* Implement `ChannelMessageEvent#isDesignatedFirstMessage`
https://twitch.uservoice.com/forums/310201-chat/suggestions/43598730--test-first-participation-highlight-in-creator-mo

feat: identify first time chatters within ChannelMessageEvent

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
common/src/main/java/com/github/twitch4j/common/enums/TwitchLimitType.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Previously `AUTH`s were not ratelimited
* Add `authRateLimit`/`ircAuthBucket` and don't open connections in `TwitchChat` until a limit token has been consumed (blocking)
https://dev.twitch.tv/docs/irc/guide#rate-limits

feat: implement the irc auth rate limit

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CustomReward.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/CustomRewardEncodeMixIn.java

* Fixes #501 
* Apply `@JsonUnwrapped` to `CustomReward`'s `MaxPerStreamSetting`, `MaxPerUserPerStreamSetting`, and `GlobalCooldownSetting` on serialization

fix: json unwrap custom reward settings on serialization

---

build.gradle.kts
chat/build.gradle.kts
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelJoinFailureEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelRemovedPostJoinFailureEvent.java
chat/src/test/java/com/github/twitch4j/chat/ChatJoinRetryTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Should help with phantom joined channels
* On initial join attempt, put channel name in `joinAttemptsByChannelName`
* On successful join, remove channel name from `joinAttemptsByChannelName`
* If entry expires from `joinAttemptsByChannelName`, the join failed. Try again with exponential backoff (if maximum retries has not been reached)
* Add `removeChannelOnJoinFailure` option to `TwitchChat(Builder)`. Upon such a removal, fire `ChannelRemovedPostJoinFailureEvent`
* Add `maxJoinRetries` to builders
https://github.com/ben-manes/caffeine/wiki/Removal

feat: retry failed joins in irc with exponential backoff

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelStateEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RitualEvent.java

* Add `ChannelMessageEvent#isUserIntroduction`
* Deprecate `ChannelStateEvent#RITUALS`
* Deprecate `RitualEvent`
* No longer call `IRCEventHandler#onRitual` (since rituals are shut down, parsing for them is wasted computation)
* Ensure `TwitchChatBuilder.credentialManager` is not null (unrelated fix)
https://twitter.com/TwitchSupport/status/1481008097749573641
https://twitter.com/TwitchSupport/status/1481008324502073347

feat: support user intro chat experiment

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreatorGoal.java

* Add the `new_subscription` creator goals type to helix/eventsub (in unofficial pubsub it's called `NEW_SUB_POINTS`)

feat: add the new_subscription creator goals type

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java

* Add `ALLTIME` as a possible `timeAggregateUnit` for leaderboard (unofficial) pubsub
* Add tos strike as a possible video playback event type

feat: add pubsub leaderboard time unit and video playback type

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java

* https://github.com/twitchdev/issues/issues/551
* Add `ChannelInformation#getBroadcasterLogin`
https://dev.twitch.tv/docs/api/reference#get-channel-information (in example response but not documented return values)

feat: add broadcaster login to ChannelInformation

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

user messages containing one of three special strings are able to circumvent parsing into a channel message event and could potentially bypass moderation features built with twitch4j.
Thanks to @SubSide for reporting the issue.

fix: special messages can prevent triggering a ChannelMessageEvent

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AliasRestrictionUpdateData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UserModerationActionData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/AliasRestrictionUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserModerationActionEvent.java

* Implement `chatrooms-user-v1.<user-id>` unofficial pubsub topic to track user bans/unbans
* Add `scheduled` flag to `VideoPlaybackData` (unrelated)
With irc changes, this is the only way to get real-time channel ban/unban events for an individual user

feat: add unofficial chatrooms user pubsub topic

---

common/src/main/java/com/github/twitch4j/common/util/EventManagerUtils.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java

* Avoid runtime exception from validateEventManager when directly using `TwitchGraphQLBuilder`
* Set default event manager as null so it can properly be created by `validateOrInitializeEventManager`
* minor cleanup in EventManagerUtils

fix: ensure gql builder event manager has default handler

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
twitch4j/src/test/java/com/github/twitch4j/TwitchClientTest.java

Since `commandPrefixes` as marked as final, it was not included in `@AllArgsConstructor`. As a result, `@With` calls were not copying this field to new instances. Thus, after calling `withCommandTrigger`, other builder `withX` calls would result in `commandPrefixes` being reset to an empty collection.
* Make `commandPrefixes` non-final (so it is added to the builder private constructor)
* Make `commandPrefixes` a `Set` in `TwitchChatBuilder` to avoid dupes (in `TwitchChat` it is stored as a `List` for faster iteration)
* Use `setCommandPrefixes` to reduce collection operations (e.g. `addAll`)
Thanks to `Hiya#3921` for reporting

fix: make commandPrefixes non-final in builders

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Remove `@Unofficial` from moderation api endpoints previously in beta

chore: promote helix moderation api methods out of beta

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/util/ChatCrowdChant.java

* Remove `\u0001` suffix on action event messages
* Deprecate `CrowdChantInfo` (unrelated)

fix: remove control character suffix in action event message

---

graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchUnbanRequests.graphql
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchUnbanRequests.java

* Add `TwitchGraphQL#fetchUnbanRequests`
Requested by Beatz

feat: implement fetch unban requests via graphql

---

build.gradle.kts
chat/build.gradle.kts

With this change, dependabot should only make one PR for each mockito version bump
* Switch to using new mockito bom format
* Bump mockito to 4.3.1
Closes #520 and #521

chore: bump mockito to 4.3.1 and switch to the bom

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PollData.java

`java.lang.IllegalArgumentException: Cannot deserialize value of type 'com.github.twitch4j.pubsub.domain.PollData$Status' from String "TERMINATED": not one of the values accepted for Enum class: [ARCHIVED, COMPLETED, ACTIVE]`
* Add more states to `PollData.Status` (unofficial pubsub)
Thanks to `applesaph` for reporting

fix: add more status enums for pubsub polls

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackArtist.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrackWrapper.java

* Explicitly document max ids that can be passed in a single `getChannelInformation` call
* Clarify soundtrack api behavior when no track is playing
2022-02-08 update @ https://dev.twitch.tv/docs/change-log

docs: update soundtrack api javadoc by twitch revision

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

The Chat connection could end up stuck without reconnecting when losing internet access and not attempting to send any messages
- enable websocket rfc ping with a default of 15s in chat and pubsub
- add the property wsPingPeriod to all relevant builders for customization
Thanks to `Pocketpac` for reporting the issue

fix: enable ws rfc ping for chat and pubsub

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java

* Measure time between chat websocket rfc ping/pong and store in `ITwitchChat#getLatency`
Has been requested by multiple people in the discord

feat: track chat socket latency

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

Avoids the following exception from being logged on `ITwitchClient#close`:
```
[ERROR] c.g.t.chat.TwitchChat - Chat: Unexpected error in worker thread
java.lang.InterruptedException: null
at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1668)
at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:435)
at com.github.twitch4j.chat.TwitchChat.lambda$new$0(TwitchChat.java:349)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at …
```

refactor: don't block when polling ircCommandQueue

---

pubsub/build.gradle.kts
pubsub/src/main/java/com/github/twitch4j/pubsub/PubSubSubscription.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubConnectionPool.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PubSubListenResponseEvent.java

* Add `PubSubListenResponseEvent#getListenRequest`
Useful to determine which specific topic failed to listen

feat: add ability to obtain listen request from pubsub response event

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/enums/AnnouncementColor.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ModAnnouncementEvent.java

* Create and fire `ModAnnouncementEvent`
* Add `ITwitchChat#sendAnnouncement`
https://twitter.com/TwitchSupport/status/1509634525982302208

feat: support new mod announcement command

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/User.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/HypeTrainServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/ModerationServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/UsersServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/WebhooksServiceTest.java

* Deprecate `User#getViewCount`
* Deprecate `TwitchHelix#getHypeTrainEvents(String, String, Integer, String, String)`
* Remove tests for decommissioned endpoints (and convert webhook tests from websub to eventsub)
https://discuss.dev.twitch.tv/t/get-hype-train-events-api-endpoint-id-query-parameter-deprecation/37613
https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777

chore: deprecate helix user view count and hype train id query param

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/util/TwitchChatLimitHelper.java
common/src/main/java/com/github/twitch4j/common/util/BucketUtils.java
common/src/main/java/com/github/twitch4j/common/util/SneakySupplier.java
common/src/main/java/com/github/twitch4j/common/util/TwitchLimitRegistry.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/util/TwitchExtensionsErrorDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SendPubSubMessageInput.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixClientIdInterceptor.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixHttpClient.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceErrorDecoder.java

* Prevents 429's from some helix endpoints with special undocumented rate limits
* Prevents 429's from consistently hammering (general) helix endpoints (due to refill rate asymmetry)
* Restrict `banUser`/`unbanUser` calls to 100/30 bucket per channel
* Restrict `addBlockedTerm`/`removeBlockedTerm` calls to 60/60 bucket per channel
* Restrict `createClip` calls to 600/60 bucket per user
* Reduce helix bucket *refill* rate to 600/60
* Allow users to override the global helix ratelimit (to be less than 800/60, for example)
* Fix resource leak in error decoders

feat: comply with undocumented helix rate limits

---

rest-extensions/build.gradle.kts
rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensions.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/compat/ExtensionsTypeConverters.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/compat/HystrixCommandConverter.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/compat/TwitchExtensionsCompatibilityLayer.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/Channel.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ChannelList.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ConfigurationSegment.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ExtensionInformation.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ExtensionSecret.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/domain/ExtensionSecretList.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* #445 
* Create `TwitchExtensionsCompatibilityLayer` to forward calls to extensions module to helix
Maintains binary compatibility for smooth transition

feat: forward extension module calls to helix

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CrowdChant.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/FriendshipData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PresenceData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PresenceSettings.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/CrowdChantCreatedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/FriendshipEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PresenceSettingsEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserPresenceEvent.java
rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensions.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/UsersServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPool.java

* Deprecate unofficial friendship pubsub topic
* Deprecate unofficial presence pubsub topic
* Deprecate unofficial crowd chant pubsub topic
* Remove deprecated `User#getViewCount` from helix test
* More deprecated annotations for extensions module
https://help.twitch.tv/s/article/how-to-use-the-friends-feature
https://twitch.uservoice.com/forums/310201-chat/suggestions/43451310--test-crowd-chant

chore: deprecate friends and chant pubsub

---

chat/src/main/java/com/github/twitch4j/chat/events/AbstractChannelEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CheerEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/DirectCheerEvent.java

* Parse unofficial `midnightsquid` usernotice and fire `DirectCheerEvent`
https://help.twitch.tv/s/article/cheering-experiment-2022?language=en_US

feat: support experimental direct cheer usernotice

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChannelPointsReward.java

* Add `IRCMessageEvent#getPredictedChoiceIndex`
* Add `IRCMessageEvent#getPredictedChoiceTitle`
* Clarify docs for `PREDICTIONS_BLUE`/`PREDICTIONS_PINK`
Unrelated:
* Parse ambassador badge as partner
* Add `templateId` to unofficial pubsub `ChannelPointsReward`
Predictions now can have 2-10 options https://help.twitch.tv/s/article/channel-points-predictions?language=en_US#creatorfaq

feat: parse new prediction badges over irc

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java

* Disable Hystrix Circuit Breaker for TwitchHelix `banUser`/`unbanUser`
In #561, we already implemented [special](https://github.com/twitch4j/twitch4j/blob/develop/rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java#L79-L84) [logic](https://github.com/twitch4j/twitch4j/blob/develop/rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java#L131-L136) to handle 429's from these endpoints that induces a pause in further requests.
However, twitch also throws errors from this endpoint in more states that can cause needless circuit break tripping (e.g., trying to (un)ban a bunch of users that are already (un)banned), so this PR disables this hystrix behavior for these specific commands

chore: disable circuit breaker on helix bans api

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Add the ability to restrict/customize chat message limit at the channel level (rather than globally/across channels)
* Does *not* implement channel-specific limits (e.g., I want 100/30 in channelX but 20/30 in channelY) -- this is probably too niche for the library to implement (and may falsely give the impression that 100/30 and 20/30 can simultaneously be used to comply with mod & non-mod limits for unverified bots at a channel level)
* More recently verified bots no longer bypass 100/30, so forcing 100/30 per-channel compliance while allowing 7500/30 global limit is desirable
* Even for unverified bots, can be useful to restrict each channel to something lower (e.g., 10/30) so it is harder for one channel to consume the global message limit

feat: add secondary per-channel irc message limit

---

common/src/main/java/com/github/twitch4j/common/util/PaginationUtil.java
twitch4j/src/main/java/com/github/twitch4j/IClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelClipCreatedEvent.java
util/src/main/java/com/github/twitch4j/util/PaginationUtil.java

* Create `ChannelClipCreatedEvent` and fire it from `TwitchClientHelper` (given the appropriate enable method was called)
* Create `IClientHelper`
* Create `PaginationUtil`
Requested a few times on the discord; due to twitch caching, no events are fired for the first 5 mins & afterwards events are fired every ~minute (assuming new clips are being created)

feat: add clip creation event fired by client helper

---

build.gradle.kts
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelBanEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainEndEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainProgressEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserUpdateEvent.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* Add `email_verified` to `UserUpdateEvent`
* Add `banned_at` to `ChannelBanEvent`
* Add `level` to `HypeTrainBeginEvent`

feat: add eventsub fields from may 2022 update

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeLevelUp.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeProgression.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainEnd.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainLevel.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainStart.java

* Log warning spam on `last-x-experiment-event` (will implement the event at a later date when details are more clear)
* Add new `isBoostTrain`, `impressions` fields to unofficial hype train pubsub

chore: add new pubsub hype fields

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SupportActivityFeedData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SupportActivityFeedEvent.java

* Implement "last x event" experiment handling over unofficial pubsub (i.e., fire `SupportActivityFeedEvent`)
Experiment announcement https://twitter.com/TwitchSupport/status/1534272693486465027
Thanks to Laura for reporting / providing a sample message

feat: add last support event pubsub handling

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BanUsersResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUser.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/RaidRequest.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/RaidRequestList.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixHttpClient.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java

* Implement `TwitchHelix#startRaid` and `TwitchHelix#cancelRaid` (while rate limiting to 10 calls per 10 minutes)
* Add `channel:manage:raids` to `TwitchScopes`
* Add `createdAt` to `BanUsersResult` & `BannedUser`
[Endpoint beta forum post](https://discuss.dev.twitch.tv/t/new-raids-api-endpoints-are-now-in-open-beta/38866/)
[Changelog (2022-06-08)](https://dev.twitch.tv/docs/change-log)

feat: add helix raids endpoints in open beta

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/EventSubSubscriptionNameExpander.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/WebhooksServiceTest.java

* Add `userId` & `type` query params to `getEventSubSubscriptions`
* Remove `@Unofficial` annotation from `startRaid`/`cancelRaid`
[2022-06-07 changelog](https://dev.twitch.tv/docs/change-log)

feat: add user_id and type args to getEventSubSubscriptions

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* Avoid ping timer related reconnect spam & resulting queue saturation
* Ensure ping timer is reset on each connect, instead of only manual `TwitchPubSub#connect` calls
* Ensure command queue is cleared on disconnect (to avoid cases where there were remaining queued commands on a disconnect being compounded with new commands on reconnect from resending subscribed topics)
Thanks to `Pocketpac` & `Doc94` for reporting logs to diagnose the issue

fix: clear pubsub command queue on reconnect

---

client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnection.java

* Avoids a very rare edge case where a disconnect could've occurred after a ping was sent but before a pong was received, resulting in a falsely exaggerated latency value on the next pong frame (post-reconnect)

fix: reset ping tracker on websocket close

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CreatorGoal.java

* Add `Clip#getVodOffset`
* Add `GoalType#SUB_COUNT` & `GoalType#NEW_SUB_COUNT`
[2022-07-20 changelog](https://dev.twitch.tv/docs/change-log)

feat: add clip offset and new goal types

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnection.java
client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnectionConfig.java

* Connection/socket timeout previously was infinite
* Add `connectionTimeout`/`socketTimeout` to client websocket

feat: add timeout config to websocket

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Remove `@Unofficial` on new endpoints from #606
[2022‑07‑29](https://dev.twitch.tv/docs/change-log): All Twitch API endpoints introduced on 2022-07-15 have moved from public beta to general availability.

chore: promote helix chat endpoints out of beta

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
common/src/test/java/com/github/twitch4j/common/util/TwitchUtilsTest.java

* `MESSAGE_PATTERN` was incorrectly matching some messages (e.g., some whispers)
* Require tags/clientName/channel to not contain whitespace characters
* Unescape more strings in `parseBadges`
* Force `parseBadges` to split key value pairs in up to 2 parts (in case the value also contains `/`)
* Use non-regex split in `parseBadges` for improved performance

fix: improve chat regex matching

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* `ChannelClipCreatedEvent` had some unnecessary delay
* Expand upper time bound of clip search window to account for coarse (10min) truncation
Caused by official docs error: https://github.com/twitchdev/issues/issues/52

fix: adjust clip event for helix time truncation

---

build.gradle.kts
chat/build.gradle.kts
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/test/java/com/github/twitch4j/chat/ChatJoinRetryTest.java
eventsub-common/build.gradle.kts
eventsub-common/src/main/java/com/github/twitch4j/eventsub/util/EventSubVerifier.java
graphql/build.gradle.kts
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
rest-helix/build.gradle.kts
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java
twitch4j/build.gradle.kts
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Forced Caffeine use was incompatible with Android
* Switch all direct Caffeine use to the Xanthic facade
For now, we still depend on `cache-provider-caffeine` to avoid any breaking changes... users can exclude this dependency & specify a different provider

refactor: use xanthic cache facade

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java

* EventSub docs are wrong; follow count creator goal type is `follow` in practice (instead of the documented `follower`)
* Add more aliases to creator goal type enum
https://discord.com/channels/504015559252377601/776875921654546463/1006570884510781450

fix: deserialize eventsub follow goal type

---

build.gradle.kts
chat/build.gradle.kts
common/build.gradle.kts
rest-helix/build.gradle.kts

* bump com.bucket4j.bucket4j-core to v8.0.1
Changelog: https://github.com/bucket4j/bucket4j/releases/tag/8.0.1
- bucket4j changed the group id, so no automatic update from renovate: 
- they provide two artifacts now, one for jdk8 compatiblity, the default one requires jdk11+ (`bucket4j_jdk8-core` and `bucket4j-core`)

chore(deps): update dependency com.bucket4j.bucket4j-core to v8.0.1

---

build.gradle.kts

* Maven users that have added a repository to their pom that offers a 3.x snapshot version of jackson have an incompatible version of jackson resolved via the rich version declaration
* Fully exclude jackson 3.x (incl. snapshots) in the rich version declaration
* Bump preferred version of jackson to `2.13.3`
In the [rich version declaration](https://github.com/twitch4j/twitch4j/blob/6e704eae9f46ac99f94adf757617232bd5c7f2d4/build.gradle.kts#L113), we exclude jackson 3.x
However, maven [resolves](https://maven.apache.org/pom.html#Version_Order_Specification): `3-snapshot < 3`, so it allows `3.0.0-SNAPSHOT` to be selected
Further, maven [ignores](https://docs.gradle.org/current/userguide/rich_versions.html) the `prefer` version in the presence of `strictly`, unlike gradle (explaining why …

fix: prevent maven from using jackson3 snapshot

---

auth/src/main/java/com/github/twitch4j/auth/TwitchAuth.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnection.java
client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnectionConfig.java
kotlin/src/test/kotlin/com/github/twitch4j/kotlin/mock/MockChat.kt
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Allows for faster underlying socket close for applications where this is required (e.g., minecraft plugins on disable, which triggers class unloading)
* Add `closeDelay` to `WebsocketConnectionConfig`
* Don't return from `WebsocketConnection#close` until the underlying `Socket` has fully closed
`nv-websocket-client` defaults `closeDelay` to `10_000` - this seems high to just wait for a single frame, so we default to `1000` instead (this part of the websocket protocol is just good manners anyway, so it's not the end of the world if formal close isn't received)

feat: allow custom websocket close delay

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelCharityDonateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelCharityDonateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* https://github.com/twitchdev/issues/issues/642
* Version for `channel.charity_campaign.donate` should be `beta` (this was [initially](https://web.archive.org/web/20220829104434/https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types) documented as `1`, but was silently changed)
* For `ChannelCharityDonateEvent`, twitch (mistakenly) sends `target_amount` as the field name for `amount`

fix(charity): resolve twitch doc issues

---

rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java

* Allow updates to `defaultAuthToken` be propagated to `TwitchHelixTokenManager`
* Use `updateCredential` rather than creating an independent copy of `defaultAuthToken`

fix(helix): avoid copying default token

---

common/src/main/java/com/github/twitch4j/common/util/DonationAmount.java

* https://github.com/twitchdev/issues/issues/642#issuecomment-1233396084
* Add `amount` as an alias for `DonationAmount.value`
extra aliases (based on naming in irc/pubsub) because i dont trust twitch anymore

chore: add aliases for DonationAmount fields

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/BitsVoting.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/PollChoice.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelPollEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PollData.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Poll.java

* Deprecate references to bits on poll objects across helix/eventsub/pubsub

chore: deprecate poll bits due to twitch change

---

common/src/main/java/com/github/twitch4j/common/util/AlternativeInstantDeserializer.java

* https://github.com/twitchdev/issues/issues/644
* https://github.com/twitchdev/issues/issues/347
* Adds yet another branch to the unconventional timestamp parser for helix teams endpoints, as a result of a new non-standard timestamp format being sent

fix: parse latest time format of helix teams

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

* Switches `String#split` (regex-based) to `StringUtils#split` (non-regex) for better performance in `TwitchChat#onTextMessage`
Achieved 9.5% faster parsing in my testing

perf: avoid regex split on chat message

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftedMultiMonthSubCourtesyEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MultiMonthGiftRedeemEvent.java

* Add `MultiMonthGiftRedeemEvent`
Since no actual money is exchanged at the time of the event, we use a separate event from `SubscriptionEvent`

feat: add MultiMonthGiftRedeemEvent

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/HostOffEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/HostOnEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/InboundHostEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Host.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/HostList.java

* Deprecate hosts
https://help.twitch.tv/s/article/how-to-use-host-mode?language=en_US#faq

chore: deprecate hosts due to twitch announcement

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* `getChannelChatBadges` was changed to not require a broadcaster token; update the javadoc accordingly
https://twitch.uservoice.com/forums/310213-developers/suggestions/43614432-allow-access-to-the-get-channel-chat-badges-endp

docs: reflect looser auth for getChannelChatBadges

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ListModsEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ListVipsEvent.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Deprecate irc commands that will be removed on 2023-02-18 in favor of helix equivalents
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

chore: deprecate irc commands due to twitch announcement

---

renovate.json

* Avoid logback 1.4.x (as it uses Java 11+ / Jakarta EE) by renovate
https://docs.renovatebot.com/configuration-options/#allowedversions

chore: ignore logback 1.4.x for renovate bumps

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelCharityDonateEvent.java

https://github.com/twitchdev/issues/issues/646
Treat `id` as an *alias* (instead of property name) for `campaignId` in `ChannelCharityDonateEvent` (to smoothly transition on 2022-09-20)
2022-09-16 Changelog entry:
```
Breaking change to the Beta [channel.charity_campaign.donate](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelcharity_campaigndonate) EventSub subscription type:
The id field of the [Charity Donation Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event) object will change to campaign_id to better reflect its content on Tuesday, September 20 at 1:00pm PDT.
```

chore: treat id as alias in charity eventsub

---

graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchModsQuery.graphql
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchVipsQuery.graphql
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchMods.java
graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchVips.java

* Add `TwitchGraphQL#fetchMods`
* Add `TwitchGraphQL#fetchVips`
* Twitch intends for non-mods to be able to read mods/vips (in the webchat interface)
* IRC version of these commands is being removed in Feb 2023

feat: fetch mods and vips over gql

---

chat/build.gradle.kts
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java

* Add a library which supports named capture groups.
Android doesn't support named capture groups [before API 26](https://developer.android.com/reference/java/util/regex/Pattern#group-name).

fix: support named capture groups on Android

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreateShoutoutData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ShoutoutTargetCallToAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/CreateShoutoutEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ShoutoutCreatedEvent.java

* Implement unofficial `shoutout.<channel-id>` pubsub topic
https://twitter.com/TwitchSupport/status/1574867514080763927
Not yet implemented (delegated to another PR): activity feed event for an incoming shoutout

feat: add unofficial shoutout pubsub topic

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java

* Parse payment details for Twitch experiment that allows users to pay for their chat to appear in chat for longer (similar to a moderator pinned message, but costs money)
https://twitter.com/TwitchSupport/status/1575603152908427272

feat: parse experimental elevated chat payment details

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelCharityDonateEvent.java

* https://github.com/twitchdev/issues/issues/642#issuecomment-1295432538
* Add `charity_name` and `charity_logo` to `ChannelCharityDonateEvent`
Marked as `@Unofficial` as these fields do not appear in the eventsub docs (but are present in helix)

feat: add charity name and logo to eventsub

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/DirectCheerEvent.java

* Handle new `msg-param-exponent` & `msg-param-currency` tags in `DirectCheerEvent`
* Round 2 of `midnightsquid` allows for non-USD direct cheers
* If the currency is not USD, we don't provide a corresponding bits value (0), as we don't keep track of currency exchange rates

fix: handle new direct cheer tags for currency

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Game.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/GamesServiceTest.java

* Add `igdb_id` to helix `Game` object (returned from `getGames`/`getTopGames`)
* Add `getGames` method supporting `igdb_id` query param
* Deprecate old `getGames` method without `igdb_id` query param
2022‑11‑21 changelog entry: https://dev.twitch.tv/docs/change-log

feat: add IGDB support in helix games api

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscriptionStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ModeratorEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ShieldModeCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShieldModeBeginEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShieldModeEndEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaShieldModeBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaShieldModeEndType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ShieldModeStatus.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ShieldModeStatusWrapper.java

* ~~https://github.com/twitchdev/issues/issues/698~~
* Add Shield Mode beta helix endpoints: get status & update status
* Add Shield Mode beta eventsub subscription types: begin & end
2022-12-02 changelog entry: https://dev.twitch.tv/docs/change-log

feat: add shield mode helix and eventsub beta support

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutomodEnforceCheckList.java

* Make all args constructor in `AutomodEnforceCheckList` public (was not due to `@Builder`)

chore: add public all args constructor in AutomodEnforceCheckList

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java

* Promote `low-trust-users` pubsub topic to official status, following twitchdev announcement
https://cdn.discordapp.com/attachments/143001431388061696/1025110131312177233/unknown.png

chore: promote suspicious users pubsub to official

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
twitch4j/src/main/java/com/github/twitch4j/IClientHelper.java

* Warn that `TwitchHelix#getFollowers` will soon be deprecated in favor of more restricted `TwitchHelix#getFollowedChannels` (requiring scoped user oauth) & `TwitchHelix#getChannelFollowers` (requiring scoped mod oauth)
https://www.twitch.tv/videos/1604648673?t=0h36m30s
Note: when `TwitchHelix#getFollowers` is decommissioned by Twitch, we'll just point it at `getFollowedChannels` / `getChannelFollowers` (depending on what args were specified)

docs: warn upcoming deprecation of helix getFollowers

---

build.gradle.kts

- Explicitly declare places where manifest is a dependency
- normalize runtime classpath analysis of manifest
These changes resolved most parts of the build that Gradle refused to build incrementally, or cache. On my local machine, the time for repeated `check` executions went from 13 seconds to 0.7 seconds.
If you have any questions/concerns, let me know!
Note: I did not check the contributing guidelines because the link in the readme goes to a dead link, so if there are any issues with style or formatting, I'm happy to fix them.
Here's a build scan of the current master (second build): https://scans.gradle.com/s/esrc625h6w7gw
Here's a build scan of this fork (also second build): https://scans.gradle.com/s/dxxpiwazvenyi

Improve build cacheability

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShieldModeBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShieldModeEndType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Remove `@Unofficial`/`Beta` from helix/eventsub shield mode endpoints/topics
[2023‑01‑10 Changelog Entry](https://dev.twitch.tv/docs/change-log/)

chore: promote shield mode from beta to official

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java

https://github.com/twitchdev/issues/issues/708
* Add `tags` to `Stream`/`ChannelSearchResult`/`ChannelInformation`
[2023‑01‑10 Changelog Entry](https://dev.twitch.tv/docs/change-log/)

feat: add custom tags to helix responses

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreateShoutoutData.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/CreateShoutoutDataTest.java

* Closes #705
* Allow `targetUserCTAInfo` to be an empty string

fix(pubsub): parse shoutout without call to action

---

build.gradle.kts

* `io.freefair.lombok`, `com.coditory.manifest`, `com.github.johnrengelman.shadow` plugins applied to the root project, but never used
*  `javadoc` task configured for root project, but never used
* `jar` and `javadoc` tasks implicitly depend on `manifest` output which breaks the build cache
* `manifest` task from `com.coditory.manifest` plugin implemented incorrectly(does not declare outputs) which caused all dependent tasks to execute
* `manifest` task produces different output every time it's executed
* `javadoc` task configured with the absolute path for `options.overview` arg, which prevents cache from being reused in case of project relocation(moved to different dir, or reuse of build-cache generated by CI)
* Use `apply(false)` in root project plugins block - speeds up project …

chore: improve gradle caching

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUser.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserNewMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTreatmentUpdate.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTypes.java

* Add javadocs for POJOs of pubsub low-trust-users
* Add `AutomodCaughtMessage.Fragment.emoticon` (freshly documented)
* Add `LowTrustUser.sharedBanChannelIds` (freshly documented)
* Add `LowTrustUserTypes` (freshly documented)
2023-02-03 Changelog Entry: https://dev.twitch.tv/docs/change-log/

docs: add suspicious users pubsub javadocs

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelFollowV2Condition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelFollowType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelFollowType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelFollowTypeV2.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/EventSubNotificationTest.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/InboundFollow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/InboundFollowers.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/OutboundFollow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/OutboundFollowing.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
rest-tmi/src/test/java/com/github/twitch4j/tmi/TMIServiceTest.java

* Deprecate `TwitchHelix#getFollowers` (this is being killed in August)
* Add `TwitchHelix#getChannelFollowers`
* Add `TwitchHelix#getFollowedChannels`
* Deprecate eventsub `ChannelFollowType` (this is being killed in August)
* Add eventsub `BetaChannelFollowType` (this *can* be actively subscribed to until Feb17)
* Add eventsub `ChannelFollowTypeV2` (this *cannot* be subscribed to until Feb17)
* Add new required scope to read channel followers: `TwitchScopes.HELIX_CHANNEL_FOLLOWERS_READ`
* Document specific date that `TwitchMessagingInterface#getChatters` will be permanently decommissioned
https://discuss.dev.twitch.tv/t/follows-endpoints-and-eventsub-subscription-type-are-now-available-in-open-beta/43322/

feat: add scoped read follows beta api

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShoutoutCreateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShoutoutReceiveType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Promote shoutout eventsub from beta to v1
* Remove `@Unofficial` from `TwitchHelix#sendShoutout`
2023-02-09 changelog entry: https://dev.twitch.tv/docs/change-log/

chore: promote shoutout api out of beta

---

twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandHelixForwarder.java

As Twitch has pushed back the IRC deprecation final date to Feb24 (and the current `ENABLE_AFTER` is already tripped), we can also push back the automatic time-based toggle for the irc => helix command forwarding. On Feb21, there is a 24-hour temporary shutdown period (and no other brown-outs scheduled after Feb16), so this may be a natural point to update `ENABLE_AFTER`
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486/83

chore: delay enabling command forwarder until february 21

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java

* https://github.com/twitchdev/issues/issues/597
* Restore the intended 800/60 helix bucket refill rate (was throttled in https://github.com/twitch4j/twitch4j/commit/4627bdb61ba35c643feb718a61cc8add660adb4c due to a bug on Twitch's end)
Updated logs can be found at https://gist.github.com/iProdigy/d5d22f598bf9888e79c30302c19d76a5 - 1659 calls were executed over 124.4 seconds while the remaining header stayed relatively constant, implying the correct rate of 800/60.

chore: restore helix refill rate after twitch fix

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixDecoder.java

* `TwitchHelixRateLimitTracker#updateRemaining` wasn't being called
* Close response body even when `InputStream` fails to be instantiated
* Read `Ratelimit-Remaining` from response headers (instead of request)

fix(helix): read remaining header from correct object

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

...
* Javadoc comment changed. 
* It is now more obvious in which order the return data is returned (move information to top).
* The note for the first paramter has been changed so that it now applies to the limit parameter (name change).
...

docs: improve TwitchHelix#getClips javadoc

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/CampaignEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelFromToEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/CustomRewardEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/EventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ModeratorEventSubCondition.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/condition/EventSubConditionEqualsTest.java

* `TwitchEventSocket#unregister` may not succeed when two subscriptions are the same except their condition object has an optional field & one sub has it set to an empty string while the other sub has it set to null.
* `TwitchEventSocket#register` may attempt a duplicate subscription when the only difference is the value of an optional field in the condition object such that one is empty string while the other is null.
* Define equals/hashCode for eventsub condition objects that include optional fields such that null string and empty string are considered equivalent.

fix(eventsub): looser equality on optional condition fields

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/SubscriptionWrapper.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocketPool.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchSingleUserEventSocketPool.java

* After `TwitchEventSocketPool#unregister`, `poolBySub` was not cleaned up so memory would not be freed and `TwitchEventSocketPool#register` could not be called again for the same subscription
* Remove subscription => pool mapping on successful `TwitchEventSocketPool#unregister` calls
Thanks to @Awakened-Redstone for debugging

fix: cleanup poolBySub on eventsocket pool unregister

---

build.gradle.kts

* use the new syntax for relocation after `ConfigureShadowRelocation` was removed in 8.1.0

fix: use new shadowJar relocation syntax

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamTag.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamTagList.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java

* Deprecate `TwitchHelix#getStreamTags` (just returns empty array as of today)
* Deprecate `TwitchHelix#getAllStreamTags` (just returns empty array as of today)
* Deprecate `TwitchHelix#replaceStreamTags` (decommissioned as of today)
* Propagate deprecated tag to return types
* Remove associated test cases
2023-02-28 changelog entry: https://dev.twitch.tv/docs/change-log/

chore(helix): deprecate more tag_id references

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CodeStatus.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CodeStatusList.java

* Deprecate `TwitchHelix#getCodeStatus`
* Deprecate `TwitchHelix#redeemCode`
2023-02-27 changelog entry: https://dev.twitch.tv/docs/change-log

chore(helix): deprecate entitlement code endpoints

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandHelixForwarder.java

* When helix, chat, and chat-command-to-helix forwarder are enabled without `chatAccount` or `defeaultAuthToken` specified, a NPE was thrown.
* Don't instantiate `ChatCommandHelixForwarder` if no token is specified (as all of the calls require an user access token, so automatic app access token couldn't be used)

fix: avoid NPE when forwarder is missing token

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubChannelEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubUserChannelEvent.java

* https://github.com/twitchdev/issues/issues/738
* Allow `broadcaster_X` to alias for `broadcaster_user_X` in eventsub events, given twitch documentation inconsistencies
Inconsistency example: https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event

chore(eventsub): define aliases for broadcaster event fields

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ViewerMilestoneEvent.java

* Fire `ViewerMilestoneEvent` unofficial chat event
https://help.twitch.tv/s/article/experiments?language=en_US
```
Viewer Milestone Cues: This experiment will highlight viewer milestones, if they opt in, to streamers so they can give a shoutout to their viewers accomplishments, like watch streaks, possibly creating more personalized relationships with their viewers.
```

feat: parse viewer milestone events sent to chat

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/VideoServiceTest.java
util/src/main/java/com/github/twitch4j/util/EnumUtil.java

* Update `TwitchHelix#getVideos` to allow a list of ID's to be queried in one call. Also we change the index of the `limit` argument to avoid "Ambiguous method reference" issues
Reported by @Skillkiller

feat(helix): allow querying multiple video ids

---

chat/src/main/java/com/github/twitch4j/chat/enums/NoticeTag.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/domain/SocketCloseReason.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityPointsGoal.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/FriendshipData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PollsEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Cheermote.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandRegistry.java

* Use `EnumUtil.buildMapping` across relevant enums (follow-up from #749)

refactor: use buildMapping util across enums

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java

* `getSubscriberMonths` yields empty for founders
* Also read subscriber months from founders badge information
The subscription tier is not sent by Twitch in the IRC message, so `getSubscriptionTier` will still yield empty

fix(chat): read subscriber months for founders

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadge.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadgeSet.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatBadgeSetList.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
twitch4j/src/test/java/com/github/twitch4j/TwitchClientTest.java

* Add `title`, `description`, `click_action`, and `click_url` to helix badge POJO
* Update javadocs for helix badge classes
* Deprecate undocumented badges endpoints in `TwitchMessagingInterface`
* Deprecate full `TwitchMessagingInterface` module
https://discuss.dev.twitch.tv/t/legacy-badges-endpoint-shutdown-details-and-timeline-june-2023/44621

feat(helix): include new badge fields

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java

* Migrate to `wss://eventsub.wss.twitch.tv/ws` (requires t4j release before May 15)
https://discuss.dev.twitch.tv/t/update-required-for-eventsub-websockets-beta-connection-url

chore(eventsub): upgrade to non-beta websocket url

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelJoinEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelLeaveEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java

* Sometimes upon joining a channel, instead of twitch sending us many `JOIN`'s, we receive `NAMES` list. This PR converts the `NAMES` response into `ChannelJoinEvent`'s
https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#NAMES

fix(chat): fire join events from 353 names list

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShieldModeBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ShieldModeEndType.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Add `moderator:read:shield_mode` & `moderator:manage:shield_mode` to `TwitchScopes`

chore: add shield mode scopes to enum

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* All founders were assumed to be active subscribers
* Use `subscriber` tag to assign `CommandPermission.SUBSCRIBER`

fix: detect whether founders are subscribed or not

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioTrack.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/RadioEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackAlbum.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackArtist.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrack.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrackWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistMetadataList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackPlaylistTracksList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackSource.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackTrack.java

* Deprecate `getSoundtrackCurrentTrack`, `getSoundtrackPlaylist`, `getSoundtrackPlaylists` helix endpoints due to Twitch EOL
https://discuss.dev.twitch.tv/t/withdrawal-of-twitch-api-endpoints-for-soundtrack/

chore: deprecate soundtrack apis

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java

* Don't parse `badge-info` tag until `IRCMessageEvent#getBadgeInfo` is called
Saves some compute/memory as users don't access badge info for most messages

perf(chat): lazily parse badge info

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* If a tag value included `=`, the value would be truncated
* Remove `rawTags` field (avoids calling `parseTags` twice)
* Deprecate `getRawTags` (simply returns `tags` now)
The maps assigned to `tags` and `rawTags` were equal, despite rawTags having `Object` values (they were all strings)

perf(chat): avoid duplicated tags parsing

---

common/src/main/java/com/github/twitch4j/common/util/EscapeUtils.java
common/src/test/java/com/github/twitch4j/common/util/EscapeUtilsTest.java

* `\a` should be unescaped as `a`
* `\` at end of string should be unescaped as empty string
(however, neither of these issues occur with observed twitch data)
* Rewrite `EscapeUtils#unescapeTagValue`
https://ircv3.net/specs/extensions/message-tags.html

perf: optimize EscapeUtils#unescapeTagValue

---

common/src/test/java/com/github/twitch4j/common/util/TwitchUtilsTest.java

* Failure from TwitchUtilsTest L30
* Badge without `/` is treated as mapping to null. Badge with `/` but empty string following is treated as mapping to empty string
Caused by https://github.com/twitch4j/twitch4j/pull/792/files#diff-a9e9acd3d58099d349009372f2077b33189d03474a18543dbca513925f4b1541L162 (quirky implementation differences of `String#split` and `StringUtils#split`)

chore: update badge parsing test

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ReplyableEvent.java

* `ReplyableEvent#reply` should reply within existing threads when possible (otherwise, reply directly to the message)
Requested by @MineTrainDevelopment

feat(chat): reply in thread when possible

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CharityDonationEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftedMultiMonthSubCourtesyEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/util/ChatCrowdChant.java
chat/src/test/java/com/github/twitch4j/chat/TwitchChatTest.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java
common/src/main/java/com/github/twitch4j/common/util/ChatReply.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Convert `IRCMessageEvent#tags` from `Map<String, String>` to `Map<String, CharSequence>`
Depends upon #791
Preemptive refactor that enables a faster implementation of `parseRawMessage` in another PR; this PR does not contain any `String` -> `CharBuffer` micro-optimizations
```
Benchmark                               Mode  Cnt   Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  14.704 ± 1.010  us/op
MessageParserBenchmark.parse1kTags      avgt    4   3.241 ± 0.155  us/op
```
```
Benchmark                               Mode  Cnt   Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  14.745 ± 0.442  us/op
MessageParserBenchmark.parse1kTags      avgt    4   3.254 ± 0.050  us/op
```

refactor(chat): treat tag value as CharSequence

---

rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java

* NPE in `TwitchHelixTokenManager` caused by `withClientId(null)` from bad user code (or lack of a default client id in `TwitchEventSocket`)
* Avoid stringifying a null client_id passed to helix

fix(helix): avoid NPE from withClientId(null)

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/util/EventSubConditionConverter.java

* Possible NPE if a user manually subscribes to an eventsub type that does not have library support yet
* Don't call `SubscriptionType#getConditionClass` in `EventSubConditionConverter.getCondition` if the subscription type is null
Caused by https://github.com/twitch4j/twitch4j/blob/c8599cc47e4defa66c0f043f77dcab00c29ff12a/eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscription.java#L105-L106 (`SubscriptionTypes.getSubscriptionType` can yield null, and the value is still passed to `EventSubConditionConverter.getCondition`)

fix(eventsub): avoid NPE when subscription type is unknown

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/ContentClassification.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/BetaChannelUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Add `channel.update` beta eventsub subscription type
2023-06-29 changelog entry https://dev.twitch.tv/docs/change-log/
Docs are lacking & I had to determine the possible `content_classification_labels` empirically. Also these values don't follow eventsub's `lower_snake_case` standard for enums, so I suspect they may change in the future

feat(eventsub): add channel.update beta subscription type

---

chat/src/jmh/java/com/github/twitch4j/chat/parser/MessageParserBenchmark.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/TwitchEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/util/MessageParser.java
chat/src/test/java/com/github/twitch4j/chat/ChatJoinRetryTest.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java
kotlin/src/test/kotlin/com/github/twitch4j/kotlin/chat/ChatExtensionsTest.kt

* Rewrite IRC message parsing approach from regex to manual splitting
```
Benchmark                               Mode  Cnt   Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  13.751 ± 0.088  us/op
MessageParserBenchmark.parse1kTags      avgt    4   2.620 ± 0.130  us/op
```
```
Benchmark                               Mode  Cnt  Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  1.702 ± 0.038  us/op
MessageParserBenchmark.parse1kTags      avgt    4  1.007 ± 0.008  us/op
```

perf(chat): remove regex from message parsing

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/FollowEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/UsersServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/IClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPool.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Client helper would've stopped tracking followers come August 3rd
* Use `TwitchHelix#getFollowedChannels` in `TwitchClientHelper` (rather than the deprecated `TwitchHelix#getFollowers`)
https://discuss.dev.twitch.tv/t/follows-endpoints-and-eventsub-subscription-type-are-now-available-in-open-beta/43322

feat: migrate client helper to new followers endpoint

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPool.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Increase max subscriptions per socket to 300 from 100
* Remove `@ApiStatus.Experimental` on event socket
https://discuss.dev.twitch.tv/t/eventsub-websockets-are-now-out-of-beta-and-generally-available/46527

chore: promote eventsub websocket out of beta

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUpdateV2Event.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelUpdateV2Type.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* Update `channel.update` beta eventsub type to v2
2023-07-17 changelog entry: https://dev.twitch.tv/docs/change-log/

chore(eventsub): promote channel.update from beta to v2

---

chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/AbstractChannelEvent.java

* Deprecate `AbstractChannelEvent#ban`, `AbstractChannelEvent#timeout`, `AbstractChannelEvent#unban`

chore: deprecate mod commands in AbstractChannelEvent

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/SubscriptionWrapper.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java

* Allow eventsub subscriptions to be registered with null EventSubTransport (`EventSubSubscription#setTransport` in `TwitchEventSocket#register` was not reflected in `SubscriptionWrapper`)
* `SubscriptionWrapper` should delegate getters to the held `EventSubSubscription` rather than copying the fields, which ensures any setters called on the underlying subscription are reflected in the wrapper (and reduces memory consumption)

fix: allow IEventSubSocket#register with null transport

---

.gitignore
build.gradle.kts
common/build.gradle.kts
common/build/generated/sources/buildConfig/main/com/github/twitch4j/common/config/Twitch4JBuildConstants.java
common/src/main/java/com/github/twitch4j/common/config/Twitch4JGlobal.java

Uses a gradle plugin to generate a class with build constants (project-version). This will ensure that the userAgent header will always report the proper version in the future.
i added the generated class with `0.0.0` as placeholder to ensure no errors show up when checking the project out pre-build.

chore: project version build constant

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/util/MessageParser.java

* null-check on channelId before channel name lookup
* use `ConcurrentHashMap` in parse test-cases to ensure identical behavior
Our test case didn't catch this because `Collections.emptyMap` allows null-key lookups while the `ConcurrentHashMap` used in the real code doesn't / throws a NPE.

fix: npe when parsing global user state in channelName lookup

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubConnectionPool.java
pubsub/src/main/java/com/github/twitch4j/pubsub/enums/PubSubType.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PubSubAuthRevokeEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/RevocationTest.java

* Don't try to LISTEN to revoked topics on reconnects
* Handle and fire event on new PubSub `AUTH_REVOKED` message type
https://dev.twitch.tv/docs/pubsub/#authorization-revoked (added on 2023-06-15)

feat(pubsub): add auth revoke event

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

...
* Change `is_recurring` to `duration` in the list of required properties to create a scheduled broadcast
...
`is_recurring` is not a required value to the [Twitch Helix API](https://dev.twitch.tv/docs/api/reference/#create-channel-stream-schedule-segment), but `duration` is. Attempting to call `createStreamScheduleSegment` without `duration` results with the Helix API error `[3:responseBody={"error":"Bad Request","status":400,"message":"Missing required parameter \"duration\""}]`.

update createStreamScheduleSegment documentation

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/util/MessageParser.java
chat/src/test/java/com/github/twitch4j/chat/util/MessageParserTest.java

* Reduce string/array allocations in `TwitchChat#onTextMessage(String)` via `MessageParser.consumeLines`

perf: split irc messages more efficiently

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
common/src/main/java/com/github/twitch4j/common/enums/HypeChatLevel.java

* Remove `@Unofficial` from `ChannelMessageEvent#getElevatedChatPayment`
* Add `ChannelMessageEvent#getHypeChatLevel`
2023-07-19 changelog entry https://dev.twitch.tv/docs/change-log/

feat: add hype chat level and duration to ChannelMessageEvent

---

build.gradle.kts
chat/build.gradle.kts
client-websocket/build.gradle.kts
eventsub-common/build.gradle.kts
eventsub-websocket/build.gradle.kts
pubsub/build.gradle.kts
rest-extensions/build.gradle.kts
rest-helix/build.gradle.kts
rest-kraken/build.gradle.kts
rest-tmi/build.gradle.kts
twitch4j/build.gradle.kts

Publishing shaded jars for `common`, `auth`, ... or some of the deprecated modules is not needed.
This limits the publication of shaded jars to the following modules:
- twitch4j
- chat
- helix
- pubsub
- eventsub-websocket

chore: limit shadowJar publication to twitch4j, chat, helix, pubsub, eventsub-websocket

---

eventsub-websocket/build.gradle.kts

* `:twitch4j-eventsub-websocket:shadowJar` produces a jar where the `com.github.twitch4j.eventsub.socket` package is relocated
* Relocate `com.github.twitch4j.eventsub.socket` to itself, so the package is not moved to the shaded packaged when building the module-specific shadow jar
`relocate(...) { exclude(...) }` approach did not work, so this trick is used instead

fix: avoid eventsocket relocation for module shadow jar

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Use the latest broadcaster login name in `ChannelGoLiveEvent`, `ChannelGoOfflineEvent`, `ChannelChangeTitleEvent`, `ChannelChangeGameEvent`, `ChannelViewerCountUpdateEvent` (in case the broadcaster changes their username while the application is running)
* `Stream#getUserLogin` did not exist when this conditional branch was originally written
* Same exact change cannot be made for clips / follow events since broadcaster login name is not exposed by Twitch in these endpoints
* If user has client helper running stream listener for a channel alongside follow/clips listener, updated username *will* also apply to follow/clip events

fix(clienthelper): reflect name changes in live events

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanSharingPermissions.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanSharingSettings.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/BanSharingSettingsUpdateEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/BanSharingSettingsTest.java

* `Unparsable Message: MESSAGE|PubSubResponsePayload(topic=low-trust-users.modId.chanId,message=PubSubResponsePayloadMessage(type=bans_sharing_settings_update,...`
* Fire `BanSharingSettingsUpdateEvent`
Relevant first-party interfaces

feat(pubsub): add ban sharing settings update event

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java

* `TwitchHelixRateLimitTracker` was not updated with `Ratelimit-Remaining` header for `HystrixCommand<Void>` endpoints (technically not an issue unless a user has multiple `TwitchHelix` instances / is using the same token across multiple applications)
* Enable `decodeVoid` for helix module
Enabled by https://github.com/twitch4j/twitch4j/pull/839 / https://togithub.com/OpenFeign/feign/pull/2131

chore(helix): sync ratelimit bucket for void endpoints

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelFollowType.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
twitch4j/src/main/java/com/github/twitch4j/IClientHelper.java

* Update docs to reflect that old follows API decommission date was pushed back to 2023-09-12
https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated

docs: update old follow api decommission date

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java

* https://github.com/twitchdev/issues/issues/822
* Force 320x180 video thumbnail resolution if video is still processing to avoid users running into error 403

chore: override thumbnail resolution for processing videos

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/WhisperThread.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/WhisperThreadUpdateEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/WhisperThreadTest.java

```
[com.github.twitch4j.pubsub.TwitchPubSub] Unparsable Message: MESSAGE|PubSubResponsePayload(topic=whispers.938512436, message=PubSubResponsePayloadMessage(type=thread, messageData=...
```
* Fire `WhisperThreadUpdateEvent`

feat(pubsub): parse whisper thread details

---

chat/src/jmh/java/com/github/twitch4j/chat/parser/MessageParserBenchmark.java
chat/src/main/java/com/github/twitch4j/chat/util/MessageParser.java

* `String#toCharArray` on the full irc message was already being done in `MessageParser.parseTags` - we move this call into `MessageParser.parse` so the array can be used for more efficient character lookups instead of using `String#charAt` (which has greater overhead from range checks and utf byte conversion)
* Remove benchmark for deprecated tag parsing method
Achieves 12% speed-up on my machine:
```
Benchmark                               Mode  Cnt  Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  1.708 ± 0.085  us/op
MessageParserBenchmark.parse1kTags      avgt    4  0.987 ± 0.061  us/op
```
```
Benchmark                               Mode  Cnt  Score   Error  Units
MessageParserBenchmark.parse1kMessages  avgt    4  1.501 ± 0.015  us/op …
```

perf: utilize char array over string in irc parser

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ReplyableEvent.java
common/src/main/java/com/github/twitch4j/common/util/ChatReply.java

* Include `reply-thread-parent-msg-id` & `reply-thread-parent-user-login` in `ChatReply` (now officially documented)
* Revert #785
Twitch updated their chat reply logic, so replying directly to a message doesn't break threads anymore: https://twitter.com/TwitchSupport/status/1687193841240059905

feat: include top level parent information in ChatReply

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/CharityCampaignDonation.java

* https://github.com/twitchdev/issues/issues/838
* Use `target_amount` to populate `CharityCampaignDonation#getAmount`

fix(helix): deserialize donation amount despite twitch using incorrect field name

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatHighlight.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChatHighlightEvent.java

* Support `channel-chat-highlights` unofficial pubsub topic
Useful to distinguish which chatters came from a raid (or other highlights twitch may add)

feat(pubsub): add unofficial chat highlights topic

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/MidrollRequest.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/MidrollRequestEvent.java

* Fire `MidrollRequestEvent` via unofficial `ads` pubsub topic

feat(pubsub): track midroll requests via unofficial ads topic

---

chat/src/main/java/com/github/twitch4j/chat/events/AbstractChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageActionEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
kotlin/src/test/kotlin/com/github/twitch4j/kotlin/chat/ChatExtensionsTest.kt

* Avoid eagerly calling `IRCMessageEvent#getClientPermissions` for `ChannelMessageEvent`/`ChannelMessageActionEvent`
`IRCMessageEvent#getClientPermissions` became lazily evaluated in #801

perf(chat): lazily evaluate permissions in channel message event

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocketPool.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* `defaultAuthToken` in `TwitchClient(Pool)Builder` is now used by `TwitchEventSocketPool` if `register` is called without a credential
Improves consistency with `TwitchSingleUserEventSocketPool` & `TwitchEventSocket`

feat: use helix default token for eventsocket pool

---

build.gradle.kts

While we do not yet depend on any v2.15 features, many maven users end up with mismatched jackson versions, which can break (de)serialization. For example, v2.15 `InstantDeserializer` references `JsonFormat.Feature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS`, which requires annotations v2.15, but versions could be mismatched, leading to: `java.lang.NoSuchFieldError: READ_DATE_TIMESTAMPS_AS_NANOSECONDS` for many helix endpoints
* Bump minimum jackson version to 2.15
Jackson usually only patches the 2 latest minor versions. Currently, that is v2.15 and v2.14, but v2.16 is about to be released, so we don't need to care about v2.14. Also v2.13 and below have CVEs, so we shouldn't worry about dropping 2.12/2.13 support

chore: bump minimum jackson version to 2.15.0

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelAdBreakCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelAdBreakBeginEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelAdBreakBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AdSchedule.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AdScheduleWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SnoozedAd.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SnoozedAdWrapper.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/AdScheduleTest.java

* ~~Endpoints are broken at launch; they require `channel:edit:commercial` when they're supposed to require `channel:read:ads`/`channel:manage:ads`~~
* ~~Endpoints are broken at launch; even with additional scopes, the endpoint just returns 404 with an empty message~~
* EventSub event field names are inconsistent across the documentation: https://github.com/twitchdev/issues/issues/850
* ~~Official scope documentation claims `channel:read:ads` is only relevant for Chat/PubSub, when in reality it's only relevant for API/EventSub~~
* Add `BetaChannelAdBreakBeginType` eventsub subscription type
* Add `TwitchHelix#getAdSchedule`
* Add `TwitchHelix#snoozeNextAd`
2023-10-19 changelog entry https://dev.twitch.tv/docs/change-log/

feat: add open beta ad schedule helix and eventsub

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/CommunitySubGift.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/PrimePaidUpgrade.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Resubscription.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/SubGift.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Subscription.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

https://discord.com/channels/504015559252377601/523675755503157248/1166536899918307410
For usernotice over eventsub:
* Rename `subPlan` to `subTier`
* Add `isPrime` to sub/resub objects
2023‑11‑07 changelog entry https://dev.twitch.tv/docs/change-log/

refactor(eventsub): use subTier over subPlan, add isPrime field

---

rest-helix/src/test/java/com/github/twitch4j/helix/domain/AdScheduleTest.java

* https://github.com/twitchdev/issues/issues/857#issuecomment-1800822567
* Add `AdSchedule` deserialization test case using actual response for a partnered account, which exhibits spec nonconformity (see below)
Currently, Twitch actually sends `snooze_refresh_at`, `next_ad_at`, `last_ad_at` as epoch seconds while documentation claims it should be RFC3339 strings. Jackson handles either format well

chore: add another test case to AdScheduleTest

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ViewerMilestoneEvent.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java

* Add `ViewerMilestoneEvent#getEarnedChannelPoints`
* Add `ViewerMilestoneEvent#getUserMessage`
* Add test case

feat(chat): include rewarded channel points in watch streak events

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Subscription.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelChatClearType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelChatNotificationType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelClearUserMessagesType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelMessageDeleteType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Promote `ChannelChatClearType`, `ChannelChatNotificationType`, `ChannelClearUserMessagesType`, `ChannelMessageDeleteType` to v1
* Remove `Subscription#getCumulativeMonths`
2023-11-15 changelog entry: https://dev.twitch.tv/docs/change-log/

chore: promote chat eventsub topics out of beta

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/GiftPayForward.java

* https://github.com/twitchdev/issues/issues/868
* Add `recipientUserId`/`recipientUserName`/`recipientUserLogin` to eventsub `GiftPayForward` model

feat(eventsub): include recipient in GiftPayForward

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/FollowingData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/FollowingEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/PooledTwitchPubSubTest.java

* https://github.com/twitchdev/issues/issues/843
* Deprecate `ITwitchPubSub#listenForFollowingEvents`
Interestingly, instead of returning `ERR_BADTOPIC`, the listen response suggests there's no error (empty string) - but no data is sent when follows occur.

chore: deprecate unofficial pubsub following topic

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelStateEvent.java

* `ChannelStateEvent` (and corresponding individual events) were only being fired upon channel JOIN - reported by MineTrain
* Ensure `ChannelStateEvent#getStates` is not empty when a single chat room setting was updated
* Ensure individual chat setting events are fired when the single setting is updated post JOIN
* Update documentation of `ChannelStateEvent` (and minor refactoring)
https://dev.twitch.tv/docs/irc/tags/#roomstate-tags

fix: populate ChannelStateEvent when single room setting changed

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Clarify that the user access token for `removeChannelModerator` can represent the target moderator (official docs erroneously claims only broadcaster token works)

docs: clarify auth for removeChannelModerator

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelAdBreakBeginEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelAdBreakBeginType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AdSchedule.java

* EventSub docs still have a `timestamp` vs. `started_at` discrepancy: https://github.com/twitchdev/issues/issues/850
* `length_seconds` was renamed to `duration` in helix and `duration_seconds` in eventsub - I don't trust this inconsistency (particularly since eventsub docs used to say `duration` in some places as another inconsistency), so will accept all three of these property names to be safe
* Promote `channel.ad_break.begin` eventsub to v1 from open beta
* Add `requester_user_login`/`requester_user_name` to `ChannelAdBreakBeginEvent`
* Promote helix ads scheduler endpoints out of open beta
* Update aliases for fields that were renamed by Twitch
2023-12-11 changelog entry https://dev.twitch.tv/docs/change-log/

chore: promote ads scheduler api out of beta

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratedChannel.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratedChannelList.java

* Add `TwitchHelix#getModeratedChannels`
2024-01-08 changelog entry https://dev.twitch.tv/docs/change-log

feat: add get moderated channels beta endpoint

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

Avoids this exception from being logged (which has no impact on the chat bot's stability) when we are told by twitch to `RECONNECT`:
```
ERROR  connection to webSocket server wss://irc-ws.chat.twitch.tv:443 failed: retrying ...
com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'irc-ws.chat.twitch.tv:443': null
at com.neovisionaries.ws.client.SocketConnector.connectSocket(SocketConnector.java:126)
at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:238)
at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:189)
at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2351)
at com.github.twitch4j.client.websocket.WebsocketConnection.connect(WebsocketConnection.java:225)
at …
```

chore(chat): queue reconnect from another thread to avoid benign exception

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatDropReason.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatMessage.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SentChatMessage.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SentChatMessageWrapper.java

* https://github.com/twitchdev/issues/issues/896
* Add `TwitchHelix#sendChatMessage`
2024‑01‑25 changelog entry https://dev.twitch.tv/docs/change-log/

feat(helix): add send chat message endpoint

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Cheer.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Message.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/MessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Reply.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelChatMessageEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelChatMessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Add `channel.chat.message` eventsub subscription type
https://discuss.dev.twitch.com/t/available-today-twitch-chat-on-eventsub-an-api-for-sending-chat-and-the-conduit-transport-method-for-eventsub/54596#an-eventsub-subscription-type-for-channel-chat-messages-1

feat(eventsub): add chat message subscription type

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PubSubRequest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/TwitchPubSubTest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/BanSharingSettingsTest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/PubSubRequestTest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/RevocationTest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/ScheduleUpdateTest.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/WhisperThreadTest.java

If token used to listen to a pubsub topic expired, the subscription would not successfully be recreated upon a reconnect (even if credential was refreshed)
* When `LISTEN` requests are sent, always use the latest access token stored in the passed `OAuth2Credential`
also fixes stability of PubSubRequest hashCode since it's used as a set key (only PubSubType and topic name/args should be used since data.auth_token is now mutable)

fix: support refreshed tokens in pubsub module

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/Emote.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeProgression.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeReward.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainEnd.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainLevel.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainParticipation.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainProgress.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainReward.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/TrainHandler.java

* Migrate `ITwitchPubSub#listenForHypeTrainEvents` to `hype-train-events-v2`
* Deprecate `ITwitchPubSub#listenForHypeTrainRewardEvents` (superceded by new `HypeTrainEnd#getRewards` method)
Web platform has recently switched to v2, mobile platforms are awaiting rollout

refactor(pubsub): migrate unofficial hype topic to v2

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BroadcastSettings.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/BroadcastSettingsUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/BroadcastSettingsHandler.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/HandlerRegistry.java

* Implement `ITwitchPubSub#listenForBroadcastSettingUpdateEvents`
Fires event if title or category is changed

feat(pubsub): add unofficial broadcast settings topic

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/Conduit.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/ConduitShard.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscriptionStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubTransport.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubTransportMethod.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/ShardStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ConduitCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ConduitShardDisabledEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ConduitShardDisabledType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocketPool.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ConduitList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ConduitShardList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ShardsInput.java

* Add new conduits helix endpoints (CRUD conduits/shards)
* Add `conduit.shard.disabled` eventsub subscription type
https://discuss.dev.twitch.com/t/available-today-twitch-chat-on-eventsub-an-api-for-sending-chat-and-the-conduit-transport-method-for-eventsub/54596#introducing-conduits-an-eventsub-transport-method-for-scale-4
Follow-up PR will create a websocket pool intended for conduit use

feat: add conduit endpoints and eventsub topic

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ModeratorEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/UnbanRequestStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UnbanRequestCreatedEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UnbanRequestResolvedEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UnbanRequestCreateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UnbanRequestResolveType.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UnbanRequest.java

* https://github.com/twitchdev/issues/issues/925
* https://github.com/twitchdev/issues/issues/926
* ~~`channel.unban_request.create` v1 doesn't fire (only beta does) -- relevant team has been informed~~
Note: for folks already using unofficial pubsub, the above issues likely prevent migration
* Add `SubscriptionTypes.UNBAN_REQUEST_CREATE`
* Add `SubscriptionTypes.UNBAN_REQUEST_RESOLVE`
Introduced as open beta on 2024-03-07
Promoted from open beta to v1 on 2024-03-15

feat(eventsub): add unban request subscription types

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Emote.java

* https://github.com/twitchdev/issues/issues/928 (supercedes #958)
* Remove `@Unofficial` marker on most helix `Emote.Type`s
* Add `Emote.Type.NONE` (would be interesting to find an empirical example of this)
2024-04-05 changelog entry https://dev.twitch.tv/docs/change-log/

chore(helix): remove unofficial marker for many emote types

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/TermUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomodSettingsUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelTermsUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubModeratorEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/AutomodSettingsUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/AutomodTermsUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Implement `automod.settings.update` eventsub subscription type
* Implement `automod.terms.update` eventsub subscription type
Added as public beta on 2024-03-07
Promoted to v1 on 2024‑03‑15
https://dev.twitch.tv/docs/change-log/

feat(eventsub): add automod settings and terms topics

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/IEventSubSocket.java

* Deprecate `IEventSubSocket#register(SubscriptionType, EventSubCondition)`
Folks can just do `b -> condition` themselves, and this method tends to cause ambiguous method call issues where folks have to use casting to specify `#register(SubscriptionType, EventSubCondition)` or `register(SubscriptionType, Function)`

chore: deprecate IEventSubSocket#register(SubscriptionType, EventSubCondition)

---

build.gradle.kts
chat/build.gradle.kts
eventsub-websocket/build.gradle.kts
pubsub/build.gradle.kts
rest-helix/build.gradle.kts
twitch4j/build.gradle.kts

* https://togithub.com/johnrengelman/shadow/issues/894 (we were already using goooler fork for previous release)
* https://togithub.com/johnrengelman/shadow/issues/908 (we'll switch to the new coordinates when available)
* Explicitly use Goooler's shadow plugin [fork](https://plugins.gradle.org/plugin/io.github.goooler.shadow) (for now)
* Exclude `module-info.class` from jackson-core
* Mark shadow jar as a multi-release jar (due to [FastDoubleParser](https://github.com/wrandelshofer/FastDoubleParser/) impls)
JDK 21+ classes were coming from jackson-core's multi-release jar - https://togithub.com/FasterXML/jackson-core/issues/1185

chore: improve shadow jar building

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AutomaticReward.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/SimpleEmote.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomaticRewardRedemptionAddEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsAutomaticRewardRedemptionAddType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Add `SubscriptionTypes.CHANNEL_POINTS_AUTOMATIC_REWARD_REDEMPTION_ADD`
Promoted to v1 on 2024-04-05
Released as public beta on 2024-03-15
https://dev.twitch.tv/docs/change-log/

feat(eventsub): add automatic reward redemption topic

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Whisper.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubUserFromToEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/WhisperReceivedEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/WhisperReceivedType.java

* Implement `user.whisper.message`
Promoted to v1 on 2024-04-05 https://dev.twitch.tv/docs/change-log/

feat(eventsub): add whisper received topic

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShieldModeBeginEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShieldModeEndEvent.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* Switch `ShieldModeBeginEvent`/`ShieldModeEndEvent` superclass to `EventSubModeratorEvent`
EventSub shield mode events have `moderator_id` but not `user_id`, so `EventSubModerationEvent` has extraneous fields for this topic

refactor(eventsub): change superclass for shield mode events

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CreatorGoal.java

* https://github.com/twitchdev/issues/issues/939
* Add `GoalType.BITS` & `GoalType.CHEERS`
* Update `CreatorGoal#getCurrentAmount` docs (tho helix doesn't report these new types yet)
2024-04-22 changelog entry https://dev.twitch.tv/docs/change-log/
Twitch announcement https://twitter.com/TwitchSupport/status/1778470287564058836

feat: support new bits cheer creator goal types

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/SentChatMessage.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/AdScheduleTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/ChannelInformationTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/SentChatMessageTest.java

* `SentChatMessage#isSent` was false, even for successful requests
* Properly deserialize `is_sent` property in `SentChatMessage`
Not critical since `dropReason == null` conveys the same information

fix: populate SentChatMessage#isSent

---

chat/src/main/java/com/github/twitch4j/chat/enums/NoticeTag.java

* Add `NoticeTag.MSG_CONCURRENT_CHANNEL_LIMIT_REACHED` (undocumented)
Twitch has lowered the number of (non-modded) channels a user can concurrently join to **100** (with the exception for verified bots being removed in a month): https://discuss.dev.twitch.com/t/giving-broadcasters-control-concurrent-join-limits-for-irc-and-eventsub/

chore: add msg_concurrent_channel_limit_reached to NoticeTag

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AutomaticReward.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/MessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelChatMessageEvent.java

* Add eventsub support for upcoming twitch experimental automatic rewards: animate my message, send gigantified emote, trigger celebration animation
2024-05-22 changelog entry https://dev.twitch.tv/docs/change-log/
i expect all of these to be reverted or largely disabled by broadcasters

feat(eventsub): add new automatic reward types

---

chat/src/main/java/com/github/twitch4j/chat/enums/NoticeTag.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ChatModerationAction.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UserModerationActionData.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatDropReason.java

* PubSub: add warning support for `chat_moderator_actions` and `chatrooms-user-v1`
* Chat: Add `NoticeTag.MSG_WARNED`
* Helix: Update `ChatDropReason` javadoc
No official documentation on this feature yet, but announced at https://x.com/TwitchSupport/status/1798403074350002447
No helix endpoint yet; see https://twitch.uservoice.com/forums/310213-developers/suggestions/48491402-provide-an-api-to-trigger-the-new-warning-system-t

feat: add events for new chat warnings feature

---

pubsub/src/main/java/com/github/twitch4j/pubsub/events/HypeTrainCooldownExpirationEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/TrainHandler.java

* Deprecate `HypeTrainCooldownExpirationEvent` (no longer fired by twitch)

chore(pubsub): deprecate HypeTrainCooldownExpirationEvent

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/AdScheduleTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/ChannelInformationTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/domain/StreamTest.java
util/src/main/java/com/github/twitch4j/common/util/TimeUtils.java

* Newcomers tend to assume `Stream#getThumbnailUrl` already yields a valid thumbnail (when they should be using `Stream#getThumbnailUrl(Integer, Integer)` instead)
* Add `Stream#getThumbnailUrlTemplate` and deprecate `Stream#getThumbnailUrl`
* Optimize `getThumbnailUrl(int, int)` by avoiding regex

refactor(helix): clarify Stream thumbnail url getters

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AugmentedMessage.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/EvasionEvaluation.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/SuspiciousStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/SuspiciousType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Emote.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Fragment.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/SuspiciousUserMessageEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/SuspiciousUserUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SuspiciousUserMessageType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SuspiciousUserUpdateType.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/SuspiciousUserMessageEventTest.java

* https://github.com/twitchdev/issues/issues/944
* https://github.com/twitchdev/issues/issues/947
* Add `SubscriptionTypes.CHANNEL_SUSPICIOUS_USER_MESSAGE`
* Add `SubscriptionTypes.CHANNEL_SUSPICIOUS_USER_UPDATE`
Promoted to v1 on 2024-04-12
Released as public beta on 2024-04-05
https://dev.twitch.tv/docs/change-log/

feat: add suspicious users eventsub topics

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/AdScheduleWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutoModSettingsWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CharityCampaignWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatSettingsWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SentChatMessageWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ShieldModeStatusWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SnoozedAdWrapper.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrackWrapper.java

* Reduce code duplication by extending `ValueWrapper` in more helix pojos
Classes that extend `ValueWrapper` will likely be removed in 2.0.0

refactor(helix): utilize ValueWrapper in more classes

---

auth/src/main/java/com/github/twitch4j/auth/TwitchAuth.java
auth/src/main/java/com/github/twitch4j/auth/providers/TwitchIdentityProvider.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Closes #989
* Allow `baseUrl` for `TwitchIdentityProvider` to be adjustable
sample usage:
```java
TwitchIdentityProvider tip = new TwitchIdentityProvider(clientId, clientSecret, redirectUrl, TwitchIdentityProvider.CLI_MOCK_BASE_URL);
CredentialManager credentialManager = CredentialManagerBuilder.builder().build();
credentialManager.registerIdentityProvider(tip);
TwitchHelix api = TwitchHelixBuilder.builder()
.withBaseUrl(TwitchHelixBuilder.MOCK_BASE_URL)
.withCredentialManager(credentialManager)
.withClientId(clientId)
.withClientSecret(clientSecret)
.withRedirectUrl(redirectUrl)
.build();
```

feat: allow auth requests to be directed to cli mock api

---

common/src/main/java/com/github/twitch4j/common/enums/TwitchEnum.java
common/src/main/java/com/github/twitch4j/common/util/TwitchEnumDeserializer.java
common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
common/src/test/java/com/github/twitch4j/common/enums/TwitchEnumTest.java
common/src/test/java/com/github/twitch4j/common/util/EscapeUtilsTest.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AutomodCategory.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AutomodMessageStatus.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomodMessageHoldEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomodMessageUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserMessageHoldEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserMessageUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/AutomodMessageHoldType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/AutomodMessageUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UserMessageHoldType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UserMessageUpdateType.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java
twitch4j/build.gradle.kts
twitch4j/src/test/java/com/github/twitch4j/internal/TwitchEnumVerificationTest.java

* standard twitch docs inaccuracies
* Add `SubscriptionTypes.AUTOMOD_MESSAGE_HOLD` (`automod.message.hold`)
* Add `SubscriptionTypes.AUTOMOD_MESSAGE_UPDATE` (`automod.message.update`)
* Add `SubscriptionTypes.USER_MESSAGE_HOLD` (`channel.chat.user_message_hold`)
* Add `SubscriptionTypes.USER_MESSAGE_UPDATE` (`channel.chat.user_message_update`)
Topics were released as open beta on 2024-03-07 and promoted to v1 on 2024-03-15: https://dev.twitch.tv/docs/change-log/
Follow-up to https://github.com/twitch4j/twitch4j/pull/957

feat(eventsub): add automod caught message topics

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/conduit/TwitchConduitSocketPool.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/events/ConduitShardReassociationFailureEvent.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/events/EventSocketWelcomedEvent.java

* If a websocket shard lost connection due to a transient network issue, when it eventually reconnected, it was not re-associated with the conduit from an API perspective
* On websocket reconnect, update the conduit shard in the API to point to the updated session ID.
* Fire meta event if re-association fails: `ConduitShardReassociationFailureEvent`

fix: reassociate conduit shards with pool after unexpected disconnects

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelWarningAcknowledgeType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelWarningSendType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Remove beta markers for `TwitchHelix#warnChatUser` and EventSub topics (`channel.warning.send` and `channel.warning.acknowledge`)
Promoted out of beta on 2024-07-11 https://dev.twitch.tv/docs/change-log/

chore(eventsub,helix): promote chat warnings to v1

---

buildSrc/overview-general.html
buildSrc/overview-single.html

* Broken links in javadoc overview pages
* Update links in `overview-general.html` and `overview-single.html`
Reported by @Awakened-Redstone

docs: update links in javadoc overview

---

build.gradle.kts

* support for tags `apiNote`, `implSpec` and `implNote` in javadoc config (as of now the comments do not show up)
* unify configuration for javadoc tasks (aggregateJavadoc task had slightly different settings, only relevant for our doc page)

chore: support for apiNote, implSpec and implNote in javadoc

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/AbstractChannelMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/CheerEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/DeleteMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubUpgradeEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubscriptionsEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftedMultiMonthSubCourtesyEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MirrorableEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ModAnnouncementEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/PayForwardEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/PrimeSubUpgradeEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RaidEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java
chat/src/test/java/com/github/twitch4j/chat/events/channel/IRCMessageEventTest.java

* Add `MirrorableEvent` interface, and apply it to the appropriate classes
* Avoid firing `CommandEvent` when the message was forwarded from another channel
* Refactor `IRCEventHandler` constructor to simplify testing
* Add unit test for forwarded `ChannelMessageEvent` (PRIVMSG) & `ModAnnouncementEvent` (USERNOTICE)
2024-09-10 changelog entry: https://dev.twitch.tv/docs/change-log/
IRC complement of #1032
I expect the feature to be officially announced at the upcoming TwitchCon next weekend

feat(chat): support stream together shared chat

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
common/src/test/java/com/github/twitch4j/common/util/TwitchUtilsTest.java

* Optimize `TwitchUtils.parseBadges`: allocate hash map more conservatively, avoid intermediate array creation
* Optimize `TwitchUtils.getPermissionsFromTags`: remove unnecessary `CharSequence#toString` call
* Optimize `IRCMessageEvent#getBadgeInfo`: switch `getTagValue` to `getRawTag` so `unescapeTagValue` is not called twice on the tag value (since unescape is also called by `parseBadges`)

perf: optimize chat badge parsing

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/DeleteMessageEvent.java

* Remove `MirrorableEvent` from `DeleteMessageEvent`
While `CLEARMSG` can be mirrored, none of the extra tags are populated, rendering the interface useless

chore: remove Mirrorable interface for DeleteMessageEvent

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodContentClassification.java

* `AutomodCaughtMessageData#getContentClassification` could yield `UNKNOWN`
* Add `AutomodContentClassification.SEXUAL_HARASSMENT`
Released in late July https://safety.twitch.tv/s/article/How-We-re-Combatting-Sexual-Harassment-on-Twitch?language=en_US

chore(pubsub): add automod classification category

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java

* Annotate official pubsub topics as deprecated (and scheduled for removal, if the first-party site doesn't rely upon them)
* Mark some unofficial pubsub topics as scheduled for removal (due to Twitch killing the underlying feature)
Full sunset on April 14, 2025 with shutdown windows starting in February 2025: https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043
Sunset will not impact unofficial topics (in all likelihood)

chore: deprecate official pubsub topics

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomodMessageHoldEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomodMessageUpdateEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessageData.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CaughtMessageReason.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/AutomodCaughtMessageDataTest.java

* `AutomodCaughtMessage.FragmentFlags#getParsedTopics` could yield an NPE when called for automod caught messages triggered by blocked terms
* EventSub: Add `AutomodMessageHoldEvent#containsBlockedTerm` & `AutomodMessageUpdateEvent#containsBlockedTerm`
* PubSub: Add new fields to indicate when messages are caught for containing blocked terms, and allow extraction of which terms caused the event
Twitch change was introduced on 2024-11-01: https://bsky.app/profile/zachbussey.bsky.social/post/3l7w7lwvsq62i
None of these changes have made it to the official docs yet, hence the `@Unofficial` annotation

feat: add automod event fields for blocked terms

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainEvent.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* Add `HypeTrainEvent#isGoldenKappaTrain` for eventsub
2024-11-21 changelog entry https://dev.twitch.tv/docs/change-log/
We already had this field for unofficial pubsub: #1001

feat(eventsub): add golden kappa train indicator

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClientPool.java

* Fixes thread name matching on `TwitchClientPool#close` to be the same of `TwitchClient#close`, 
* Fixes non daemon threads being left running

fix: shutdown library-created executors on TwitchClientPool close

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Message.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Poll.java

* Clarify that `Message#getEmotes` can be null
Reported at https://discord.com/channels/504015559252377601/776875921654546463/1313246244411277392

chore(eventsub): mark message emotes as nullable

---

common/src/main/java/com/github/twitch4j/common/enums/TwitchLimitType.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixHttpClient.java
rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java

* Throttle `TwitchHelix#sendChatAnnouncement` to 1 per 2 seconds
2025-01-21 changelog entry: https://dev.twitch.tv/docs/change-log/

feat(helix): honor new chat announcement ratelimit

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubscriptionsEvent.java

* Add `GiftSubscriptionsEvent#getTier` that yields `SubscriptionPlan` rather than `String`
* Add `GiftSubscriptionsEvent#getGiftId` that is equivalent to eventsub's `CommunitySubGift#getId`
Requested at https://discord.com/channels/143001431388061696/268348117919858688/1325474541731840051
sample irc message: `@system-msg=boymeetsmini\sis\sgifting\s4\sTier\s1\sSubs\sto\sDoodleBirb's\scommunity!\sThey've\sgifted\sa\stotal\sof\s14\sin\sthe\schannel!;tmi-sent-ts=1738900918148;display-name=boymeetsmini;room-id=569880943;emotes=;badge-info=subscriber/12;msg-param-community-gift-id=16548143234047877033;id=91439900-0bf7-4a81-a36e-c629c76567ef;rm-received-ts=1738900918254;user-type=;badges=subscriber/12,sub-gifter/10;msg-param-mass-gift-count=4;msg-param-goal-target-contributions=15;msg-param-goal- …

feat(chat): add parsed tier and giftId to GiftSubscriptionsEvent

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscriptionStatus.java

* https://github.com/twitchdev/issues/issues/1066
* Add `EventSubSubscriptionStatus.CONDUIT_DELETED`

chore(eventsub): add conduit_deleted sub status

---

chat/src/main/java/com/github/twitch4j/chat/events/AbstractChannelMessageEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelChatMessageEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChatMessage.java

* Allow specifying `for_source_only` in `TwitchHelix#sendChatMessage`
* Add `AbstractChannelMessageEvent#isSourceOnly` (IRC)
* Add `ChannelChatMessageEvent#isSourceOnly` (EventSub)
2025-04-10 changelog entry: https://dev.twitch.tv/docs/change-log

feat: support source only shared chat messages

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java

* Add shared viewership statistic to `VideoPlaybackEvent` (unofficial pubsub)
https://blog.twitch.tv/en/2024/12/05/shared-viewership/

feat(pubsub): add stream together view count field

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreatorGoal.java

Avoids an exception when one of these newer goal types would be deserialized
* Add more creator goal types for unofficial pubsub
* Include auto-increment flag and colors to the unofficial payload
https://help.twitch.tv/s/article/creator-goals?language=en_US

fix(pubsub): add more goal types
