twitch4j/twitch4j

README.md
build.gradle
src/main/java/me/philippheuer/twitch4j/endpoints/ChannelEndpoint.java
src/main/java/me/philippheuer/twitch4j/exceptions/RestException.java
src/main/java/me/philippheuer/twitch4j/helper/RestClient.java
src/main/java/me/philippheuer/twitch4j/helper/RestErrorHandler.java
src/main/java/me/philippheuer/twitch4j/model/Error.java
src/main/java/me/philippheuer/twitch4j/streamlabs/StreamlabsClient.java
src/main/java/me/philippheuer/twitch4j/streamlabs/endpoints/AbstractStreamlabsEndpoint.java
src/main/java/me/philippheuer/twitch4j/streamlabs/endpoints/AlertEndpoint.java
src/main/java/me/philippheuer/twitch4j/streamlabs/endpoints/DonationEndpoint.java
src/main/java/me/philippheuer/twitch4j/streamlabs/endpoints/UserEndpoint.java
src/main/java/me/philippheuer/twitch4j/streamlabs/enums/StreamlabsScopes.java
src/main/java/me/philippheuer/twitch4j/streamlabs/model/AlertCreate.java
src/main/java/me/philippheuer/twitch4j/streamlabs/model/DonationCreate.java
src/main/resources/logback.xml

* Streamlabs Donation Create
* Streamlabs Custom Alert Create
* Added Rest API Error Handling (and output/logging)

Branch: Feature/Streamlabs

---

build.gradle
src/main/java/me/philippheuer/twitch4j/TwitchClient.java
src/main/java/me/philippheuer/twitch4j/auth/CredentialManager.java
src/main/java/me/philippheuer/twitch4j/chat/IrcClient.java
src/main/java/me/philippheuer/twitch4j/chat/IrcEventHandler.java
src/main/java/me/philippheuer/twitch4j/chat/commands/Command.java
src/main/java/me/philippheuer/twitch4j/chat/commands/CommandArgument.java
src/main/java/me/philippheuer/twitch4j/chat/commands/CommandHandler.java
src/main/java/me/philippheuer/twitch4j/events/EventDispatcher.java
src/main/java/me/philippheuer/twitch4j/events/event/MessageEvent.java
src/main/java/me/philippheuer/twitch4j/model/ChannelList.java
src/main/java/me/philippheuer/twitch4j/model/GameList.java
src/main/java/me/philippheuer/twitch4j/model/IngestList.java
src/main/java/me/philippheuer/twitch4j/model/StreamFeaturedList.java
src/main/java/me/philippheuer/twitch4j/model/StreamList.java
src/main/java/me/philippheuer/twitch4j/model/StreamSingle.java
src/main/java/me/philippheuer/twitch4j/model/TeamList.java
src/main/java/me/philippheuer/twitch4j/model/UserList.java
src/main/java/me/philippheuer/twitch4j/model/VideoList.java
src/main/java/me/philippheuer/twitch4j/model/VideoTopList.java
src/main/java/me/philippheuer/util/conversion/TypeConvert.java

Some changes, to allow building chatbots using this api - or to respond/monitor the chat for any other reasons.
- Added MessageEvent
- Added CommandHandler/Command Classes and argument parser
- Added Method to write to twitch chat

Feature / Chatbot

---

src/main/java/me/philippheuer/twitch4j/events/event/irc/ClearChatEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/IRCMessageEvent.java
src/main/java/me/philippheuer/twitch4j/message/irc/listener/IRCEventListener.java

* Bans and Timeouts are triggered on `CLEARCHAT` command.
* mods can be identified via `mod` tag. (No identification badges needed) - supported only 3 badges on chat. Expected collision by other badges.
* added Clear Chat Event for referenced issue (see above)

Bugfixing TMI

---

src/main/java/me/philippheuer/twitch4j/events/event/irc/ChannelStateEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/IRCMessageEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/NoticeEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/BroadcasterLanguageEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/ChannelStatesEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/EmoteOnlyEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/FollowersOnlyEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/Robot9000Event.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/SlowModeEvent.java
src/main/java/me/philippheuer/twitch4j/events/event/irc/roomstates/SubscribersOnlyEvent.java
src/main/java/me/philippheuer/twitch4j/message/irc/ChannelCache.java
src/main/java/me/philippheuer/twitch4j/message/irc/listener/IRCEventListener.java

* `ROOMSTATE` have a spitted classes for ChannelState
* `NOTICE` will be raw. Cause there is notice when would be added for
  - Hosted by Channel
  - Setted time for Followers Only. `ROOMSTATE` returns `followers-only` tag as number in Minutes (not seconds). There is `TimeUnit` class when will be converted to seconds.
Check some added comments. Otherwise delete it, if is necessary. If you want to add some features mentioned #17 i can put it into this PR. Just say where should I put it?

Final merges to TMI

---

src/main/java/me/philippheuer/twitch4j/message/MessageInterface.java
src/main/java/me/philippheuer/twitch4j/message/irc/TwitchChat.java

...
* Deprecates partChannel (to give time to migrate from it instead of just hard removing it), and adds leaveChannel. They work in the exact same way though, compiling passes and a test implementation works fine.
...

Deprecates partChannel and adds leaveChannel 

---

src/main/java/me/philippheuer/twitch4j/message/commands/Command.java
src/main/java/me/philippheuer/twitch4j/message/commands/CommandHandler.java
src/test/java/me/philippheuer/twitch4j/message/commands/CommandHandlerTest.java
src/test/java/me/philippheuer/twitch4j/message/commands/TestCommand.java

Fix and regression test for #35

---

.gitignore

Ignores the IDE configuration file

Ignores for VSCode

---

src/main/java/me/philippheuer/twitch4j/enums/Scope.java

* [+ ] I have read and understood the [contribution guidelines](https://github.com/twitch4j/twitch4j/blob/master/.github/CONTRIBUTING.md) and I accept them.
* [+ ] This pull request follows the code style of the project
* [+ ] I have tested this feature
* Scope without name now lowerCased
...

fix Scope for lowerCase enums without name

---

docs/content/chat/send-message.md

Fix typo in docs

---

docs/content/rest-helix/streamtags-all.md
docs/content/rest-helix/streamtags-replace.md
docs/content/rest-helix/streamtags-stream.md
rest-helix/src/main/java/com/github/twitch4j/helix/ObjectToJsonExpander.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamTag.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamTagList.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java

Implement feature request described in issue #64. Specifically, adding the list of active tags on a stream returned from the getStreams method,, and adding methods for the three new tag-related endpoints.
...
* [Issue #64 ]
...
* modified method getStreams - Added mapping for the tagIds list to the Stream object.
* new method getAllStreamTags - get available Twitch stream tags.
* new method getStreamTags - get tags for the specified stream.
* new method replaceStreamTags - Replace (or clear) stream tags for specified stream.
* Added StreamTag and StreamTagList classes as new domain objects
* Added helper class ObjectToJsonExpander - a custom expander for encoding body parameters in JSON
...
Additional Information
I could not find a way to automatically map the body parameter for the …

Implement feature request described in issue #64

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java

* Fixes issues with requests being exploded instead of comma seperated

Fixed getUsersByLogin request to support multiple logins

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Moderator.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorEventList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorList.java

* [Added getModerators](https://dev.twitch.tv/docs/api/reference/#get-moderators)
* [Added getModeratorEvents](https://dev.twitch.tv/docs/api/reference/#get-moderator-events)

Added getModerators and getModeratorEvents

---

rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Host.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/HostList.java

* Add support for the /hosts endpoint of TMI with the getHosts(channelIds) and getHostsOf(targetId) methods.

Added support for /hosts endpoint of TMI

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BitsLeaderboardEntry.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Follow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamMetadata.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Subscription.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/User.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/KrakenUser.java
rest-kraken/src/test/java/kraken/endpoints/ChannelServiceTest.java
rest-kraken/src/test/java/kraken/endpoints/UsersServiceTest.java

* Breaking changes to follow twitch docs and use strings for ids instead of longs

Changed long to strings to reflect docs

---

docs/content/rest-kraken/_index.md

Fixed some incorrect wording and added more links to Twitch dev docs.

Clarify Kraken vs. Helix

---

.github/PULL_REQUEST_TEMPLATE.md

Fix typos and clarify wording.

Clarify wording

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Game.java

* Added a getBoxArtUrl method in the Game object which takes the width and the height of the game's box art to match the getThumbnailUrl() method in the Stream object.

Added getBoxArtUrl(width, height)

---

build.gradle
rest-helix/build.gradle
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CategorySearchList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformationList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Cheermote.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CheermoteList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Commercial.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CommercialList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/HypeTrainEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/HypeTrainEventList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamKey.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamKeyList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UploadEntitlementUrl.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UploadEntitlementUrlList.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/HypeTrainTopic.java
rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/TwitchWebhookTopic.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/BitsServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/ChannelServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/HypeTrainServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/SearchServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/StreamsServiceTest.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/UsersServiceTest.java

* Fixes #73 
* Fixes `TwitchHelix#getExtensionTransactions`
Announcement: https://discuss.dev.twitch.tv/t/announcing-the-latest-helix-endpoints-and-hype-train-api/26530

feat: implement new helix endpoints

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java

* Refactor `TwitchChat`
* Join anonymously when no chat account is provided

feat: join twitch chat anonymously (and refactor)

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

* Rate limit violation when reconnecting to the websocket and there are many channels to rejoin
* Delegate all channel joins through the irc command queue to ensure rate limit compliance
* Consume tokens from irc bucket for initial commands used to setup the websocket & pings (didn't bother to make this blocking, however)

fix: better chat rate limit compliance

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutomodEnforceCheck.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutomodEnforceCheckList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutomodEnforceStatus.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/AutomodEnforceStatusList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedEventList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUser.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUserList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CodeStatus.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CodeStatusList.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/ModerationServiceTest.java

Add endpoints:
* Get Code Status
* Redeem Code
* Get Banned Users
* Get Banned Events
* Check AutoMod Status

feat: implement remaining helix endpoints

---

docs/content/pubsub/_index.md
docs/content/pubsub/topic-bits-badge-unlocks.md
docs/content/pubsub/topic-bits-events.md
docs/content/pubsub/topic-channel-points-events.md
docs/content/pubsub/topic-commerce-events.md
docs/content/pubsub/topic-following-events.md
docs/content/pubsub/topic-friendship-events.md
docs/content/pubsub/topic-hype-train-events.md
docs/content/pubsub/topic-hype-train-rewards.md
docs/content/pubsub/topic-leaderboard-events.md
docs/content/pubsub/topic-moderation-events.md
docs/content/pubsub/topic-onsite-notifications.md
docs/content/pubsub/topic-poll-events.md
docs/content/pubsub/topic-presence-events.md
docs/content/pubsub/topic-public-cheer-events.md
docs/content/pubsub/topic-raid-events.md
docs/content/pubsub/topic-sub-gift-events.md
docs/content/pubsub/topic-subscribe-events.md
docs/content/pubsub/topic-user-community-points-events.md
docs/content/pubsub/topic-video-playback-events.md
docs/content/pubsub/topic-whispers.md

* Work towards #75 
* Add docs for all implemented pubsub topics, official and unofficial
This PR depends upon #152

docs: revamp pubsub documentation

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/BitsBadgeEarnedEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/PayForwardEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/PrimeGiftReceivedEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RaidCancellationEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RewardGiftEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RitualEvent.java

Handle:
* `bitsbadgetier`
* `communitypayforward`
* `primecommunitygiftreceived`
* `rewardgift`
* `ritual`
* `standardpayforward`
* `unraid`

feat: handle more USERNOTICE chat events

---

twitch4j/src/main/java/com/github/twitch4j/TwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/test/java/com/github/twitch4j/TwitchClientTest.java

* Can enable extensions api in the client builder
* The client itself will contain the api object
Docs will need to be updated at a later point

feat: allow access to extensions api from twitch client

---

docs/content/rest-helix/_index.md
docs/content/rest-helix/bits-cheermotes.md
docs/content/rest-helix/entitlements-codes.md
docs/content/rest-helix/entitlements-redeem-codes.md

* [Issue #203]
Added some markdown docs for cheermotes and codes methods

docs: add cheermotes and codes markdown docs

---

build.gradle
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java
twitch4j/src/main/java/com/github/twitch4j/events/ChannelFollowCountUpdateEvent.java

* Add `ChannelFollowCountUpdateEvent`
* Update version for okhttp and caffeine cache libraries

feat: add channel follow count update event to client helper

---

build.gradle
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
common/src/main/java/com/github/twitch4j/common/util/EventManagerUtils.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/test/java/com/github/twitch4j/TwitchClientTest.java

Require a fully configured EventManager (and just check if it's usable by twitch4j) or fully initialize a new one.
It's better to clearly split this up and not touch a eventManager instance that might be used by other libraries too.
I'm keeping this as draft to wait for the next events4j release -> https://github.com/PhilippHeuer/events4j/pull/7

fix: default event handler

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/UserStateEvent.java

* [Issue #189]
* [Implement `UserStateEvent` with badges/badgeInfo, so user of event can retrieve all needed info, and helper methods for some common cases]
* [Add USERSTATE event handler in `IRCEventHandler`]

feat: fire specialized event on USERSTATE

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
common/src/main/java/com/github/twitch4j/common/util/EscapeUtils.java
graphql/src/main/graphql/com/github/twitch4j/graphql/internal/schema.json
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java

Typos found by running `codespell -i 3 -w`, ignoring some arbitrary finds.

Fix various typos

---

common/src/main/java/com/github/twitch4j/common/util/TimeUtils.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* Resolve some edge cases in the pubsub automatic reconnect logic
https://gist.github.com/Pocketpac/a6ddbfbe4a194de1b2477fce51e75015

fix: improve pubsub automatic reconnects

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainApproaching.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainReward.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/HypeTrainApproachingEvent.java

* Add support for the `hype-train-approaching` type under the `hype-train-events-v1` pubsub topic

feat: add hype train approaching pubsub event

---

auth/src/main/java/com/github/twitch4j/auth/providers/TwitchIdentityProvider.java

* When revoking, check whether a client_id is contained within the credential before defaulting to the one passed in the constructor of TwitchIdentityProvider
* Share OkHttpClient instance across TwitchIdentityProvider's; avoids overhead of creating/deleting request pools and okhttp automatically releases idle resources

perf: optimize TwitchIdentityProvider requests and probe id on revoke

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUser.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BitsLeaderboard.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/BitsLeaderboardEntry.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CustomReward.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CustomRewardRedemption.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/DateRange.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionTransaction.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Follow.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/FollowList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Moderator.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ModeratorEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamMarkers.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java

* Include new `broadcaster_login` & `user_login` fields in a variety of helix endpoints

feat: include new login fields in helix endpoints

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelRaidType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Today `channel.raid` eventsub went from `beta` to `1`

refactor: make channel.raid eventsub official

---

rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/ChatBadge.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/ChatBadges.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/Emoticon.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/EmoticonImages.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/EmoticonList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/EmoticonSetEntry.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/EmoticonSetList.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/SimpleEmoticon.java
rest-kraken/src/main/java/com/github/twitch4j/kraken/domain/SimpleEmoticonList.java

* Add `TwitchKraken#getChatBadgesByChannel(String)`
* Add `TwitchKraken#getChatEmoticons` and `TwitchKraken#getChatEmoticonsBySet(Collection)`
* Add `TwitchKraken#getAllChatEmoticons`
https://dev.twitch.tv/docs/v5/reference/chat

feat: add kraken chat emote endpoints

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscription.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/EventSubSubscriptionList.java

* Add `cost`, `total_cost`, and `max_total_cost` fields for eventsub
https://discuss.dev.twitch.tv/t/rfc-0014-eventsub-subscription-limit-changes/30312/

feat: include eventsub cost fields for RFC 0014

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java

* Add `Video#getThumbnailUrl(int, int)`

feat: add Video#getThumbnailUrl(int, int)

---

build.gradle

* bump caffeine dependency from 2.8.6 to 2.9.0

chore: bump caffeine dependency from 2.8.6 to 2.9.0

---

rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java

* Implement the new helix fields that were added on 2020-04-15: https://dev.twitch.tv/docs/change-log

feat: include new helix fields from april 15 update

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityGoalContribution.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityPointsGoal.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/CommunityGoalContributionEvent.java

* Add support for the `community-goal-contribution` type under `community-points-channel-v1`

feat: add community goal support for channel points pubsub

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityBoostOrder.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityBoostProgression.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/CommunityBoostProgressionEvent.java

* Implement `community-boost-events-v1` unofficial pubsub topic

feat: add community boost events unofficial pubsub topic

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/util/TwitchChatLimitHelper.java

* Fixes #174 
* Instead of eating a whole thread, chat now has a similar thread model to pubsub
* Create separate bucket for join/part commands

feat: implement chat join ratelimit and improve thread efficiency

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelUnsubscribeCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUnsubscribeEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelUnsubscribeType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Support `channel.unsubscribe` beta
Announced in today's TwitchDev stream
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelunsubscribe-beta

feat: implement channel.unsubscribe eventsub beta

---

build.gradle.kts

* Bump caffeine from `2.9.0` to `2.9.1`
https://github.com/ben-manes/caffeine/releases/tag/v2.9.1

chore: bump caffeine from 2.9.0 to 2.9.1

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ExtensionBitsTransactionCreateCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ExtensionEventSubCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Product.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ExtensionBitsTransactionCreateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaExtensionBitsTransactionCreateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Support for the `extension.bits_transaction.create` eventsub beta
<https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#extensionbits_transactioncreate-beta>

feat: support extension bits transaction create eventsub beta

---

pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java

* A rarer form of the issue in #320
* Also update `lastPong` on reconnect to be extra safe

fix: resolve another rare pubsub looping edge case

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Emote.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/EmoteList.java

* ~~https://github.com/twitchdev/issues/issues/413~~
* ~~https://github.com/twitchdev/issues/issues/414~~
* Add `TwitchHelix#getChannelEmotes(String, String)`
* Add `TwitchHelix#getGlobalEmotes(String)`
* Add `TwitchHelix#getEmoteSets(String, Collection)`

feat: implement new helix emote api endpoints

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/UserAuthorizationGrantCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserAuthorizationGrantEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaUserAuthorizationGrantType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UserAuthorizationGrantType.java

* Support `user.authorization.grant` beta
Announced in today's TwitchDev stream https://www.twitch.tv/videos/1013294766?t=00h32m23s

feat: implement user authorization grant v1 eventsub

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/DeleteMessageEvent.java

feat: add chat event for single message deletion

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanEvasionEvaluation.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUser.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserNewMessage.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTreatment.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTreatmentUpdate.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SimpleUser.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/LowTrustUserNewMessageEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/LowTrustUserTreatmentUpdateEvent.java

* Add `low-trust-users.<user-id>.<channel-id>` unofficial pubsub topic
https://twitter.com/Twitch/status/1465808096865959939

feat: add low trust users unofficial pubsub topic

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanEvasionEvaluation.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUser.java

* `LowTrustUser.sender` can have `chatColor`/`badges`
* support `UNKNOWN_EVADER` in `BanEvasionEvaluation`

refactor: augment BanEvasionEvaluation and LowTrustUser.sender

---

common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java

* Add `NO_AUDIO`, `NO_VIDEO`, `MOMENTS`, `ARTIST` to `CommandPermission`
* Handle edge cases for `TWITCHSTAFF`, `SUBGIFTER`, `BITS_CHEERER`

feat: add artist, moment, accessibility badges

---

common/src/main/java/com/github/twitch4j/common/util/EventManagerUtils.java

* Helps workaround [SPIGOT-7145](https://hub.spigotmc.org/jira/browse/SPIGOT-7145)
* First only attempt to initialize `defaultEventHandler` in `initializeEventManager` (avoiding an `autoDiscovery` call, which could trigger reflection calls on classes that are not loaded... which typically isn't an issue, but bukkit's `PluginClassLoader` is "special")

refactor: avoid autoDiscovery in initializeEventManager

---

graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java

* Allow custom headers to be specified for each outbound GQL request

feat: apply custom gql headers

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Chatter.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChattersList.java
rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java

* Add `TwitchHelix#getChatters`
* Add `TwitchScopes#HELIX_CHATTERS_READ`
https://twitter.com/TwitchDev/status/1575599010131447808

feat: add helix get chatters beta endpoint

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelCharityDonateEvent.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/CharityCampaignDonation.java

* Add `id` to `ChannelCharityDonateEvent` (eventsub) & `CharityCampaignDonation` (helix)
[2023‑01‑10 Changelog Entry](https://dev.twitch.tv/docs/change-log/)

feat: add id field to charity campaign donations

---

build.gradle.kts
chat/build.gradle.kts
chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
kotlin/src/test/kotlin/com/github/twitch4j/kotlin/mock/MockChat.kt
rest-helix/src/main/java/com/github/twitch4j/helix/domain/NamedUserChatColor.java
twitch4j/build.gradle.kts
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandHandler.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandHelixForwarder.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandRateLimitType.java
twitch4j/src/main/java/com/github/twitch4j/internal/ChatCommandRegistry.java
twitch4j/src/test/java/com/github/twitch4j/internal/ChatCommandHelixForwarderTest.java
twitch4j/src/test/java/com/github/twitch4j/internal/ChatCommandRegistryTest.java

* Forward deprecated IRC command execution to Helix, come February 18, 2023
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

feat: add helix chat command forwarder

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelShoutoutCondition.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubChannelFromToEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/EventSubModerationEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ModeratorEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShoutoutCreateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ShoutoutReceiveEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaShoutoutCreateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaShoutoutReceiveType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* https://discuss.dev.twitch.tv/t/new-shoutouts-api-and-eventsub-subscription-types-are-now-in-open-beta/42906/2
* https://discuss.dev.twitch.tv/t/new-shoutouts-api-and-eventsub-subscription-types-are-now-in-open-beta/42906/7
* Add `TwitchHelix#sendShoutout` beta endpoint
* Add `channel.shoutout.create`/`channel.shoutout.receive` beta eventsub subscription types
* Add `moderator:read:shoutouts`/`moderator:manage:shoutouts` scopes
2023-01-19 changelog entry https://dev.twitch.tv/docs/change-log/

feat: add shoutout public beta support

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelCharityDonateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/CharityCampaignProgressType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/CharityCampaignStartType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/CharityCampaignStopType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Promote charity eventsub out of public beta
* Promote charity helix endpoints out of public beta
2023-01-19 Changelog Entry: https://dev.twitch.tv/docs/change-log/

chore: promote charity helix and eventsub from beta

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/events/EventSocketDeleteSubscriptionSuccessEvent.java

* Add/fire `EventSocketDeleteSubscriptionSuccessEvent`

feat(eventsocket): add delete sub success meta event

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/GlobalUserStateEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/UserStateEvent.java

* Add `IRCMessageEvent#getUserDisplayName`
* Add `IRCMessageEvent#getUserChatColor`
* Optimize some tags map reads
Requested by @MineTrainDevelopment

feat(chat): add more getters for common tags

---

chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelModEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/DirectCheerEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/HostOffEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/HostOnEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/InboundHostEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ListModsEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/ListVipsEvent.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MessageDeleteError.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/MessageDeleteSuccess.java
chat/src/main/java/com/github/twitch4j/chat/events/channel/RitualEvent.java

* `IRCEventHandler` stops checking for events to fire upon the first match
Can refine exact order in the future

perf: exit irc handler upon first event match

---

eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/IEventSubSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocket.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchEventSocketPool.java
eventsub-websocket/src/main/java/com/github/twitch4j/eventsub/socket/TwitchSingleUserEventSocketPool.java

* Add `IEventSubSocket#getLatency`
Mirrors chat/pubsub interfaces

feat: add IEventSubSocket#getLatency

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscriptionStatus.java

* https://github.com/twitchdev/issues/issues/829
* Add `EventSubSubscriptionStatus.BETA_MAINTENANCE`

chore: add BETA_MAINTENANCE to EventSubSubscriptionStatus

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* https://github.com/twitchdev/issues/issues/516
* https://github.com/twitchdev/issues/issues/545
* Clarify `query` functionality for `TwitchHelix#searchChannels`
https://dev.twitch.tv/docs/api/reference/#search-channels

docs(helix): clarify searchChannels functionality

---

pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PinnedMessage.java

* Support hype/elevated chat messages in `pinned-chat-updates-v1` unofficial pubsub topic
Thanks to occluder for the message sample: https://pastebin.com/raw/Zdvabrd3

feat(pubsub): support hype chat via pinned messages

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ScheduleUpdate.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/ScheduledAd.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/AdsScheduleUpdateEvent.java
pubsub/src/test/java/com/github/twitch4j/pubsub/domain/ScheduleUpdateTest.java

* Fire `AdsScheduleUpdateEvent` via unofficial `ITwitchPubSub#listenForAdsManagerEvents`

feat(pubsub): support unofficial ads manager topic

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
rest-helix/src/test/java/com/github/twitch4j/helix/endpoints/ClipsServiceTest.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java

* Add `Clip#isFeatured`
* Add `TwitchHelix#getClips` method with `isFeatured` parameter
2023‑09‑12 changelog entry https://dev.twitch.tv/docs/change-log/

feat: add featured clip status to helix

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java

Immediately reconnect upon receiving `RECONNECT` from Twitch, instead of waiting until the server forcibly disconnects our client

feat(chat): reconnect earlier upon being requested by twitch

---

build.gradle.kts

sets the properties to enable reproducible builds, see https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
allows us to verify the reproducibility of published archives:
- https://github.com/jvm-repo-rebuild/reproducible-central
- https://reproducible-builds.org/

chore: enable reproducible archives

---

common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Badge.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelChatNotificationEvent.java

* Add `badges` field to `ChannelChatNotificationEvent`
2023-11-07 changelog entry https://dev.twitch.tv/docs/change-log/

feat(eventsub): add badges to ChannelChatNotificationEvent

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelChatSettingsUpdateEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/BetaChannelChatSettingsUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* https://github.com/twitchdev/issues/issues/885
* Add `SubscriptionTypes.BETA_CHANNEL_CHAT_SETTINGS_UPDATE`
2024-01-08 changelog entry https://dev.twitch.tv/docs/change-log

feat: add beta chat settings update eventsub type

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UnbanRequest.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UnbanRequestList.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/UnbanRequestStatus.java

* Implement `TwitchHelix#getUnbanRequests`
* Implement `TwitchHelix#resolveUnbanRequest`
* Promote `TwitchHelix#getModeratedChannels` to v1 from open beta
https://dev.twitch.tv/docs/api/reference/#get-unban-requests
https://dev.twitch.tv/docs/api/reference/#resolve-unban-requests

feat(helix): implement unban request beta endpoints

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelChatSettingsUpdateType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Update `channel.chat_settings.update` eventsub subscription type from beta to v1
2024-03-07 changelog entry https://dev.twitch.tv/docs/change-log/

chore(eventsub): promote chat settings topic to v1

---

auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/Emote.java
rest-helix/src/main/java/com/github/twitch4j/helix/domain/EmoteList.java

* Add `TwitchHelix#getUserEmotes`
2024-03-07 changelog entry https://dev.twitch.tv/docs/change-log/

feat(helix): add user emotes endpoint

---

README.md

* use tables for module list (add eventsub and cache-api)
* remove "internal" modules
* fix badges

docs: update readme with new modules, fix badges

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelVipAddEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelVipRemoveEvent.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelVipAddType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelVipRemoveType.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java

* Implement `channel.vip.add` & `channel.vip.remove`
Promoted to v1 on 2024-04-05 https://dev.twitch.tv/docs/change-log/

feat(eventsub): add vip add and remove topics

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/OutboundFollow.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/OutboundUnfollow.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/OutboundFollowPubSubEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/OutboundUnfollowPubSubEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/FollowsHandler.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/HandlerRegistry.java
pubsub/src/test/java/com/github/twitch4j/pubsub/handlers/FollowsHandlerTest.java

* Add `ITwitchPubSub#listenForFollows` to fire `OutboundFollowPubSubEvent`/`OutboundUnfollowPubSubEvent`

feat(pubsub): add outbound follows unofficial topic

---

chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java

* Add `cosmic-abyss` to chat javadoc for `ChannelMessageEvent#getAnimationId`
https://x.com/TwitchSupport/status/1826287530725064795

docs(chat): add new animation id

---

build.gradle.kts
chat/build.gradle.kts
eventsub-websocket/build.gradle.kts
pubsub/build.gradle.kts
rest-helix/build.gradle.kts
twitch4j/build.gradle.kts

* Update shadow plugin to v8.3.2
https://plugins.gradle.org/plugin/com.gradleup.shadow
https://github.com/GradleUp/shadow?tab=readme-ov-file#gradle-shadow
https://github.com/GradleUp/shadow/compare/8.1.1...8.3.2

chore: update gradle shadow plugin to v8.3.2

---

chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
chat/src/main/java/com/github/twitch4j/chat/enums/MirroredMessagePolicy.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Add `MirroredMessagePolicy` for chat module, which will drop duplicated shared chat events by default

feat(chat): add mirrored message policy configuration

---

kotlin/src/test/kotlin/com/github/twitch4j/kotlin/mock/MockChat.kt

* Fixes test cases for ktx module

chore: update mock test for kotlin module

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SharedChatParticipant.java
pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SharedChatSession.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SharedChatPubSubEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SharedChatSessionCreatedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SharedChatSessionEndedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SharedChatSessionStartedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/SharedChatSessionUpdatedEvent.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/HandlerRegistry.java
pubsub/src/main/java/com/github/twitch4j/pubsub/handlers/SharedChatHandler.java

* Add `shared-chat-channel-v1` unofficial pubsub topic

feat(pubsub): add shared chat unofficial topic

---

build.gradle.kts

* Configure conditional signing to work towards automated reproducible builds

chore: skip signing when publishing to maven local

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/ContentClassification.java

* Avoids `ContentClassification.UNKNOWN`
* Add `ContentClassification.POLITICS`
Added on 2024-11-01 https://twitter.com/TwitchSupport/status/1852370050335887512

feat: add new politics content classification

---

pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
pubsub/src/main/java/com/github/twitch4j/pubsub/events/PubSubListenResponseEvent.java
twitch4j/src/main/java/com/github/twitch4j/ITwitchClient.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java

* Mark more pubsub references as scheduled for removal
based on further investigation, it seems that even unofficial pubsub will be killed

chore: add more pubsub deprecation warnings

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/AutomaticReward.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/chat/Emote.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/AutomaticRewardRedemptionAddV2Event.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelPointsAutomaticRewardRedemptionAddV2Type.java
eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
eventsub-common/src/test/java/com/github/twitch4j/eventsub/events/EventSubEventTest.java

* Add `SubscriptionTypes.CHANNEL_POINTS_AUTOMATIC_REWARD_REDEMPTION_ADD_V2`
Promoted to v2 on 2025-02-27

feat(eventsub): add channel.channel_points_automatic_reward_redemption.add v2 topic

---

eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/SuspiciousType.java

* Remove `@JsonAlias` from `SuspiciousType` after docs update clarified the correct enums
* Add javadocs to `SuspiciousType`
2025-03-20 changelog entry: https://dev.twitch.tv/docs/change-log/

chore: clean up SuspiciousType after docs update

---

rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java

* Add `TwitchHelix#getEventSubSubscriptionById`
Enabled by new query param added on 2025-05-09: https://dev.twitch.tv/docs/change-log/

feat(helix): add getEventSubSubscriptionById
